"""Gate on the companion-archetype triad -- the third leg alongside the builder and the overrides.

    C:\\Python310\\python.exe Backend/scripts/validate_companion_archetypes.py

Map #18, ticket #40. `companion_archetypes.json` is GENERATED by
`build_companion_archetypes.py` from prose heuristics, and
`companion_archetypes_overrides.json` is the hand-authored file that wins over it. This asserts
that the pair is internally consistent and still agrees with its inputs.

It is written to be useful DURING sign-off, not only after it: the overrides file is being filled
in by hand from `docs/companion_archetype_signoff.md`, and a typo'd archetype name, an invented
effect, or a curated species that does not exist are exactly the mistakes that pass unnoticed
otherwise. Sign-off progress is a WARN, so the gate is not red for the whole review.

Vocabulary is imported from `validate_companion_data.py`, which owns it (#38's closed sets), rather
than restated here.
"""
import json
import os
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import build_companion_archetypes as bca                          # noqa: E402
from validate_companion_data import (                             # noqa: E402
    CREATURE_TYPES, EFFECTS, FLAGS, OUTCOMES,
)

ROOT = HERE.parents[1]
ARCHETYPES = ROOT / "Backend/json/archetypes.json"
SPECIES = ROOT / "Backend/json/animal_choices.json"
ALIASES = ROOT / "Backend/json/companion_species_aliases.json"

errors = []
warnings = []


def load(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def species_index():
    """Every species key, plus the archetype spellings that alias onto one."""
    data = load(SPECIES)
    keys = {name.lower() for tier in data.values() for name in tier}
    alias_data = load(ALIASES) if ALIASES.exists() else {}
    aliases = {k.lower(): v.lower() for k, v in (alias_data.get("aliases") or {}).items()}
    unavailable = {k.lower(): v for k, v in (alias_data.get("unavailable") or {}).items()}
    return keys, aliases, unavailable


def resolve_species(name, keys, aliases):
    name = str(name).strip().lower()
    if name in keys:
        return name
    if name in aliases and aliases[name] in keys:
        return aliases[name]
    # "giant weasel" <-> "weasel, giant" is the file's own convention; try it before failing.
    if "," in name:
        flipped = " ".join(p.strip() for p in reversed(name.split(",")))
        if flipped in keys:
            return flipped
    else:
        parts = name.split()
        if len(parts) == 2:
            flipped = f"{parts[1]}, {parts[0]}"
            if flipped in keys:
                return flipped
    return None


def check_keys_resolve(entries, source_label, archetypes):
    """No dead keys -- every "Class/Archetype" must still exist after a rescrape."""
    for key, entry in entries.items():
        if "/" not in key:
            errors.append(f'{source_label}: {key!r} is not "Class/Archetype"')
            continue
        cls, name = key.split("/", 1)
        if cls not in archetypes:
            errors.append(f"{source_label}: {key!r} names class {cls!r}, absent from "
                          f"archetypes.json")
        elif name not in archetypes[cls]:
            errors.append(f"{source_label}: {key!r} names an archetype absent from "
                          f"archetypes.json -- dead key after a rescrape?")
        if not isinstance(entry, dict):
            errors.append(f"{source_label}: {key!r} is {type(entry).__name__}, not an object")


def check_vocabulary(entries, source_label):
    for key, entry in entries.items():
        if not isinstance(entry, dict):
            continue
        effect = entry.get("effect")
        if effect is not None and effect not in EFFECTS:
            errors.append(f"{source_label}: {key!r} effect = {effect!r} is not in {EFFECTS}")
        for item in entry.get("effects") or []:
            one = item.get("effect") if isinstance(item, dict) else item
            if one not in EFFECTS:
                errors.append(f"{source_label}: {key!r} effects[] holds {one!r}, "
                              f"not in {EFFECTS}")
        ctype = entry.get("creature_type")
        if ctype is not None and ctype not in CREATURE_TYPES:
            errors.append(f"{source_label}: {key!r} creature_type = {ctype!r} is not in "
                          f"{CREATURE_TYPES}")
        if effect == "creature_type" and not ctype:
            errors.append(f"{source_label}: {key!r} claims effect 'creature_type' but names no "
                          f"creature")
        outcome = entry.get("outcome")
        if outcome is not None and outcome not in OUTCOMES:
            errors.append(f"{source_label}: {key!r} outcome = {outcome!r} is not in {OUTCOMES}")
        for flag in entry.get("flags") or []:
            if flag not in FLAGS:
                errors.append(f"{source_label}: {key!r} flag {flag!r} is not in {FLAGS}")


def check_species_pools(entries, source_label, keys, aliases, unavailable):
    """#38: a curated species the data lacks is a HARD failure, not a fallback."""
    for key, entry in entries.items():
        if not isinstance(entry, dict):
            continue
        pool = entry.get("species_pool")
        if pool is None:
            continue
        if not isinstance(pool, list):
            errors.append(f"{source_label}: {key!r} species_pool is "
                          f"{type(pool).__name__}, expected a list")
            continue
        for species in pool:
            low = str(species).strip().lower()
            if low in unavailable:
                record = unavailable[low]
                note = (record.get("guidance") or record.get("reason") or "")
                if isinstance(record, str):
                    note = record
                note = " ".join(str(note).split())
                errors.append(f"{source_label}: {key!r} names {species!r}, recorded in "
                              f"companion_species_aliases.json as unavailable. {note}")
                continue
            if resolve_species(species, keys, aliases) is None:
                errors.append(f"{source_label}: {key!r} names species {species!r}, absent from "
                              f"animal_choices.json (add an alias if it exists under another "
                              f"spelling)")


def check_generated_is_current(on_disk):
    """The generated file must be exactly what the builder produces -- never hand-edited."""
    # Must mirror build_companion_archetypes.main() exactly, including the verification pass --
    # otherwise every run reports a stale file that is in fact current.
    rebuilt, _, _ = bca.apply_verified(bca.build())
    rebuilt, _ = bca.apply_overrides(rebuilt)
    if json.dumps(rebuilt, sort_keys=True) != json.dumps(on_disk, sort_keys=True):
        missing = sorted(set(rebuilt) - set(on_disk))
        extra = sorted(set(on_disk) - set(rebuilt))
        detail = ""
        if missing:
            detail += f" missing {len(missing)} (e.g. {missing[:3]})"
        if extra:
            detail += f" unexpected {len(extra)} (e.g. {extra[:3]})"
        errors.append("companion_archetypes.json is stale or hand-edited -- it does not match "
                      "what build_companion_archetypes.py produces."
                      + (detail or " content differs")
                      + " Re-run the builder; record decisions in the overrides file.")


def check_completeness(on_disk, archetypes):
    """No archetype whose prose touches a bond feature may be left unclassified.

    `none` is an explicit verdict, not the absence of one -- that distinction is what makes this
    assertion mean anything when the scrape is refreshed.
    """
    for cls in bca.GRANTORS:
        for name, body in (archetypes.get(cls) or {}).items():
            if not isinstance(body, dict):
                continue
            own_keys, sentences = bca.bond_features(body)
            if not own_keys and not sentences:
                continue
            key = f"{cls}/{name}"
            if key not in on_disk:
                errors.append(f"completeness: {key!r} touches a bond feature but is not "
                              f"classified")
            elif not on_disk[key].get("effect"):
                errors.append(f"completeness: {key!r} carries no effect verdict")


def main():
    generated_path = bca.OUT
    if not generated_path.exists():
        print(f"{generated_path} does not exist -- run build_companion_archetypes.py first")
        return 1

    on_disk = load(generated_path)
    overrides = load(bca.OVERRIDES) if bca.OVERRIDES.exists() else {}
    archetypes = load(ARCHETYPES)
    keys, aliases, unavailable = species_index()

    # Overrides are merged INTO the generated file, so checking both reports every override
    # problem twice and names the generated file for a mistake that lives in the hand-authored
    # one. Check overrides on their own, and the generated file only where it is not overridden.
    generated_only = {k: v for k, v in on_disk.items() if k not in overrides}
    for entries, label in ((generated_only, "companion_archetypes.json"),
                           (overrides, "companion_archetypes_overrides.json")):
        check_keys_resolve(entries, label, archetypes)
        check_vocabulary(entries, label)
        check_species_pools(entries, label, keys, aliases, unavailable)
    check_generated_is_current(on_disk)
    check_completeness(on_disk, archetypes)

    signed = sum(1 for e in on_disk.values() if isinstance(e, dict) and e.get("signed_off"))
    if signed < len(on_disk):
        warnings.append(f"sign-off in progress: {signed} of {len(on_disk)} archetypes signed off "
                        f"(docs/companion_archetype_signoff.md -> "
                        f"companion_archetypes_overrides.json)")
    multi = [k for k, e in on_disk.items()
             if isinstance(e, dict) and len(e.get("effects") or []) > 1]
    if multi:
        warnings.append(f"{len(multi)} archetype(s) carry more than one effect; a consumer that "
                        f"reads only `effect` sees the primary verdict alone")

    for message in warnings:
        print(f"WARN: {message}")
    if errors:
        print()
        for message in errors:
            print(message)
        print(f"FAILED: {len(errors)} problem(s)")
        return 1

    counts = {}
    for entry in on_disk.values():
        if isinstance(entry, dict):
            counts[entry.get("effect")] = counts.get(entry.get("effect"), 0) + 1
    summary = ", ".join(f"{effect} {counts.get(effect, 0)}" for effect in EFFECTS)
    print(f"OK: {len(on_disk)} archetypes classified ({summary}); "
          f"{len(overrides)} override(s); no dead keys, vocabulary clean, "
          f"generated file current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
