#Only small amounts of data, we don't want to have massive 1000+ lines long of data here

# where you want characters to be from:
skills = ["acrobatics",
"appraise",
"bluff",
"climb",
"craft",
"diplomacy",
"disable device",
"disguise",
"escape artist",
"fly",
"gather information",
"handle animal",
"heal",
"intimidate",
"knowledge arcana",
"knowledge dungeoneering",
"knowledge engineering",
"knowledge geography",
"knowledge history",
"knowledge local",
"knowledge nature",
"knowledge martial",
"knowledge nobility",
"knowledge planes",
"knowledge religion",
"linguistics",
"perception",
"perform",
"profession",
"ride",
"sense motive",
"sleight of hand",
"spellcraft",
"stealth",
"survival",
"swim",
"use magic device",
"artistry",
"profession",
"lore"]

lore = ["Goblin Lore",
"Dragon Lore",
"Vampire Lore",
"Werewolf Lore",
"Orc Lore",
"Kraken Lore",
"Undead Lore",
"Elemental Lore",
"Demon Lore",
"Fey Lore",
"Construct Lore",
"Aberration Lore",
"Giants Lore",
"Minotaur Lore",
"Drow Lore",
"Mind Flayer Lore",
"Beholder Lore",
"Lycanthropy Lore",
"Angelic Lore",
"Devil Lore",
"Serpentine Creatures Lore",
"Myconid Lore",
"Genie Lore",
"Kobold Lore",
"Undead Lore",
"Slaad Lore",
"Troll Lore",
"Centaur Lore",
"Insectoid Lore",
"Spider Lore",
"Hag Lore",
"Treant Lore",
"Rakshasa Lore",
"Mimic Lore",
"Phoenix Lore",
"Elemental Plane Lore",
"Yuan-ti Lore",
"Banshee Lore",
"Gnoll Lore",
"Harpy Lore",
"Manticore Lore",
"Medusa Lore",
"Griffon Lore",
"Aarakocra Lore",
"Bulette Lore",
"Cockatrice Lore",
"Cyclops Lore",
"Lizardfolk Lore",
"Kraken Lore",
"Turtle Lore",
"Merfolk Lore",
"Kraken Lore",
"Sahuagin Lore",
"Sea Serpent Lore",
"Aboleth Lore",
"Kuo-Toa Lore"
]

formulas = {
    'favored_terrains': 'ceil((character.c_class_level - 2) / 5)',
    'favored_enemies': '1 + floor(character.c_class_level / 5)',
    'manuevers': 'floor((character.c_class_level + 1)/4)'
}

armor_type_mapping = {
    ('monk', 'unchained_monk'): None,
    ('rogue', 'bard', 'brawler'): 'L',
    ('barbarian', 'unchained_barbarian', 'ranger'): 'M',
    (): 'H'
}

enhancement_bonus_mapping = {
    2000: 1,
    8000: 2,
    18000: 3,
    32000: 4,
    50000: 5,
    72000: 6,
    98000: 7,
    128000: 8,
    162000: 9,
    200000: 10,
}
# caster spell known progression:
# wizards know 3 + INT mod + 2(per level) spells

# add later
# "occultist", "kineticist", "medium", "mesmerist", "psychic","spiritualist",
base_classes = ["alchemist", "antipaladin", "arcanist", "barbarian", "barbarian _unchained", "bard", "bloodrager", "brawler", "cavalier", "cleric", "druid", "fighter", "gunslinger", "hunter", "inquisitor", "investigator", "magus", "monk", "monk _unchained", "ninja",  "oracle", "paladin",  "ranger", "rogue", "rogue _unchained", "samurai", "shaman", "shifter", "skald", "slayer", "sorcerer",  "summoner", "summoner _unchained", "swashbuckler", "vigilante", "warpriest", "witch", "wizard"]

divine_casters = ['antipaladin', 'cleric', 'druid', 'oracle', 'hunter' ,'inquisitor', 'paladin', 'ranger', 'shaman', 'warpriest']
#caster spells per day progression

#must match the same order as the weapon_groups_region section
regions = ["Tal-Falko","Dolestan","Sojoria","Ieso", "Spire", "Feyador", "Esterdragon", "Grundy", "Dust-Cairn", "Kaeru no Tochi"]
races = ["Human", "Aasimar", "Catfolk", "Dragonborn", "Dhampir", "Drow", "Duergar", "Elf", "Fetchling", "Goblin", "Gnome", "Halfling", "Dwarf", "Half-Elf", "Half-Orc", "Hobgoblin", "Ifrit", "Kitsune", "Kobold", "Monkey Goblin", "Orc", "Oread", "Ratfolk", "Sylph", "Tengu", "Tiefling", "Undine", "Wayang", "Loxophant", "D-Ziriak", "Tortugan"]
weapon_groups = ['Axes', 'Blades, Heavy', 'Blades, Light', 'Bows', 'Close', 'Crossbows', 'Double', 'Firearms', 'Flails', 'Hammers', 'Monk', 'Natural', 'Polearms', 'Siege Engines', 'Spears', 'Thrown', 'Tribal']

manuevers = ["Bull Rush", "Dirty Trick", "Disarm", "Drag", "Grapple", "Overrun", "Reposition", "Steal", "Sunder", "Trip"]

# make weapon group into a dictionary that depends on regions:
weapon_groups_region = {
    'Tal-Falko': ['Swords', 'Axes', 'Bows'],
    'Dolestan': ['Maces', 'Spears', 'Wands'],
    'Sojoria': ['Swords', 'Bows', 'Wands'],
    'Ieso': ['Axes', 'Maces', 'Spears'],
    'Spire': ["Greathammer", "Starknife", "Flail", "Scythe", "Dagger", "Shortsword" ],
    'Feyador': ['Bow', 'Spear'],
    'Esterdragon': ['Polearm','Staff'],
    'Grundy': ['Sling', 'Club'],
    'Dust-Cairn': ['Spear','Natural Weapon', 'Lance', 'Greatsword', 'Rapier'],
    'Kaeru no Tochi': ['katana', 'Kusarigama', 'Tonfa', 'Hooked Lance', 'Nodachi', 'Kama', 'Wakizashi']
}

hit_dice = {
    "d12": ["Barbarian", "Warder"],
    "d10": ["Anti-Paladin","Bloodrager","Brawler","Fighter","Cavalier","Gunslinger","Paladin","Ranger","Samurai","Slayer","Swashbuckler", "Unchained Monk", "Warlord","Zealot"],
    "d8": ["Alchemist","Bard","Cleric","Druid","Hunter","Inquisitor","Investigator","Magus","Medium","Mesmerist","Mystic","Ninja","Occultist","Oracle","Psychic","Rogue","Shaman","Skald","Spiritualist","Summoner","Stalker","Warpriest"],
    "d6": ["Arcanist","Psychic","Sorcerer","Witch","Wizard"]
}

#add options
languages = ['Abyssal', 'Aklo', 'Aquan', 'Auran', 'Celestial', 'Common',  'Draconic', 'Drow Sign Language', 'Dwarven', 'Elven', 'Giant', 'Gnoll', 'Gnome', 'Goblin', 'Grippli', 'Halfling', 'Ignan', 'Infernal', 'Kelish', 'Orc', 'Protean', 'Sphinx', 'Sylvan', 'Tengu', 'Terran','Undercommon', 'Wayang']
#add options
all_deities = {
"good_deities" : [ "Abadar",    "Cayden Cailean",    "Desna",    "Erastil",    "Iomedae",    "Irori",    "Sarenrae",    "Shelyn",    "Torag",    "Amaznen",    "Angradd",    "Apsu",    "Chaldira Zuzaristan",    "Chamidu",    "Chevaghol",    "Dorasharn",    "Eritrice",    "Falayna",    "Ghenshau",    "Green Faith",    "Gruhastha",    "Hathor",    "Hei Feng",    "Horus",    "Kofusachi",    "Kurgess",    "Lady Nanbyo",    "Lysianassa",    "Milani",    "Nalinivati",    "Nethys",    "Norgorber",    "Osiris",    "Pharasma",    "Qi Zhong",    "Ragdya",    "Razmir",    "Sivanah",    "Spirits of the Land",    "Sulak",    "Sun Wukong",    "Tsukiyo",    "Wadjet",    "Yamatsumi",    "Ydersius",    "Zon-Kuthon"]
,
"neutral_deities" : ["Apsu",
"Aroden",
"Besmara",
"Brigh",
"Calistria",
"Cayden Cailean",
"Desna",
"Erastil",
"Ghlaunder",
"Gozreh",
"Grandmother Spider",
"Groteus",
"Iomedae",
"Irori",
"Lamashtu",
"Nethys",
"Norgorber",
"Pharasma",
"Qi Zhong",
"Sarenrae",
"Shelyn",
"Torag",
"Urgathoa",
"Wadjet",
"Ydersius",
"Zyphus"]
,
"evil_deities" : ["Asmodeus",
"Baphomet",
"Dahak",
"Droskar",
"Ghlaunder",
"Gorum",
"Groetus",
"Lamashtu",
"Norgorber",
"Rovagug",
"Szuriel",
"Urgathoa",
"Zon-Kuthon"]
}

#types of casters
caster_mod = {
        "int_casters": ['alchemist','wizard' ],
        "wis_casters": ['cleric','druid'],
        "cha_casters": ['bard','paladin','sorcerer']

}

#all_deities = ['Abadar', 'Achaekek', 'Alseta', 'Ameiko Kaijitsu', 'Apsu', 'Aroden', 'Asmodeus', 'Black Butterfly, The', 'Brigh', 'Calistria', 'Cayden Cailean', 'Chaldira Zuzaristan', 'Chamidu', 'Daikitsu', 'Dahak', 'Desna', 'Elion', 'Erastil', 'Ghlaunder', 'Gorum', 'Gozreh', 'Groetus', 'Gruhastha, The', 'Hanspur', 'Hei Feng', 'Iomedae', 'Irori', 'Jaidi', 'Jingxi', 'Kabriri', 'Kazutal', 'Kelizandri', 'Ketephys', 'Kofusachi', 'Lama, The', 'Lamashtu', 'Magrim', 'Milani', 'Minderhal', 'Naderi', 'Nalinivati', 'Nethys', 'Nivi Rhombodazzle', 'Norgorber', 'Old-Mage Jatembe', 'Oras', 'Orcus', 'Pharasma', 'Qi Zhong', 'Ragathiel', 'Razmir', 'Rovagug', 'Sarenrae', 'Sivanah', 'Sivanah, The', 'Skrymir', 'Sokhna', 'Sun Wukong', 'Thamir Gixx', 'Thremyr', 'Torag', 'Urgathoa', 'Uskyeria', 'Wadjet', 'Weydan', 'Ydersius', 'Yuelral', 'Zagnexapan', 'Zargos', 'Zon-Kuthon' ]
#alignments = ["Chaotic good", "Chaotic neutral", "Chaotic evil", "Lawful good", "Lawful neutral", "Lawful evil", "Neutral good", "True Neutral", "Neutral evil"]

alignments = {
        "CG": "chaotic good",
        "CN": "chaotic neutral",
        "CE": "chaotic evil",
        "NG": "neutral good",
        "N": "true neutral",
        "NE": "neutral evil",
        "LG": "lawful good",
        "LN": "lawful neutral",
        "LE": "lawful evil"
    }

alignment_exclusion = {
        'chaotic': 'lawful',
        'lawful': 'chaotic',
        'good': 'evil',
        'evil': 'good'
    }

amount = {
  'arcanist':{
    'basic': [1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51]
  },
  'bloodrager':{
    'feats': [7,10,13,16,19,22,25,28,31,34,37,40,43,46,49]
  }
  ,
  'fighter': {
    'armor_train': [7,11,15,19,23,27,31,35,39,43,47,51],
    'weapon_train': [9,13,17,21,25,29,33,37,41,45,49,53]
  },
  'shaman':{
    'basic': [2, 4, 8, 10, 12, 16, 18, 20, 24, 26, 28, 32, 34, 36, 40, 42, 44, 48, 50, 52]
  }, 
  'witch':{
    'basic': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]
  },
  'sorcerer': {
        'feats': [7,13,19,25,31,37,43,49]
  }
}

hair_colors = ['Black', 'Brown', 'Blond', 'Red', 'White', 'Grey']
hair_types = ['Curly',  'Bald', 'Wavy', 'Straight', 'Flowing', 'Frizzy', 'Spiky', 'Touseled', 'Unkempt','Bald']
eye_colors = ['Amber', 'Blue', 'Brown', 'Grey', 'Green', 'Hazel']
appearance = [  "Athletic",

  "Beautiful",
  "Beefy",
  "Big-boned",
  "Blemished",
  "Blonde",
  "Blue-eyed",
  "Blushing",
  "Bony",
  "Bow-legged",
  "Braided hair",
  "Broken nose",
  "Brunette",
  "Bulging eyes",
  "Bushy eyebrows",
  "Butterfly tattoo",
  "Chubby",
  "Clean-shaven",
  "Clumsy",
  "Colored hair",
  "Confident",
  "Cross-eyed",
  "Curly hair",
  "Dapper",
  "Dark-skinned",
  "Dazzling",
  "Defined cheekbones",
  "Delicate",
  "Dimpled",
  "Dirty",
  "Distinguished",
  "Double chin",
  "Droopy eyes",
  "Dumpy",
  "Elegant",
  "Emaciated",
  "Energetic",
  "Enthusiastic",
  "Exotic",
  "Exquisite",
  "Fierce",
  "Fiery",
  "Filthy",
  "Fine hair",
  "Flabby",
  "Flat nose",
  "Flawless skin",
  "Freckled",
  "Friendly",
  "Frizzy hair",
  "Full lips",
  "Gangly",
  "Gap-toothed",
  "Gelled hair",
  "Geometric tattoo",
  "Glamorous",
  "Gleaming",
  "Glistening",
  "Glossy hair",
  "Gorgeous",
  "Graceful",
  "Grinning",
  "Grimacing",
  "Grizzled",
  "Hairy",
  "Handsome",
  "Happy",
  "Harmonious",
  "Harsh",
  "Hazel-eyed",
  "Healthy",
  "Heart-shaped face",
  "Hefty",
  "Henna tattoo",
  "Hollow cheeks",
  "Homely",
  "Honey-colored eyes",
  "Hooded eyes",
  "Huge ears",
  "Hunched",
  "Husky",
  "Icy blue eyes",
  "Impish",
  "Infectious smile",
  "Intricate tattoos",
  "Jagged scar",
  "Jaunty",
  "Jaw-dropping",
  "Jowly",
  "Juicy lips",
  "Keen-eyed",
  "Knobby knees",
  "Lanky",
  "Large forehead",
  "Large nose",
  "Laughing eyes",
  "Lean",
  "Leathered skin",
  "Leggy",
  "Lethargic",
  "Light hair",
  "Lithe",
  "Lively",
  "Lopsided smile",
  "Loud",
  "Lovely",
  "Luminous",
  "Lumpy",
  "Luscious",
  "Madcap",
  "Majestic",
  "Manicured nails",
  "Masculine",
  "Meaty",
  "Melancholy",
  "Mellow",
  "Messy hair",
  "Mighty",
  "Mild",
  "Mirthful",
  "Mischievous",
  "Missing teeth",
  "Mohawk",
  "Muscular",
  "Narrow-eyed",
  "Natural beauty",
  "Neat",
  "Nervous",
  "Noble",
  "Nose ring",
  "Oily skin",
  "Old-fashioned",
  "Open",
  "Overweight",
  "Pallid",
  "Pensive",
  "Perky",
  "Piercings",
  "Pimply",
  "Plain",
  "Plump",
  "Polished",
  "Ponytail",
  "Portly",
  "Posh",
  "Pot-bellied",
  "Pouty lips",
  "Pretty",
  "Prim",
  "Protruding ears",
  "Pudgy",
  "Puffy eyes",
  "Ragged",
  "Rakish",
  "Raspy voice",
  "Ravishing",
  "Receding hairline",
  "Refined",
  "Regal",
  "Ripped",
  "Rough hands",
  "Ruddy complexion",
  "Rugged",
  "Runny nose",
  "Sad",
  "Sallow",
  "Salt-and-pepper hair",
  "Sassy",
  "Scrawny",
  "Scruffy",
  "Sculpted",
  "Seductive",
  "Self-assured",
  "Sensitive",
  "Serene",
  "Sexy",
  "Shapely",
  "Sharp features",
  "Shaved head",
  "Shifty eyes",
  "Shimmering eyes",
  "Shiny hair",
  "Short",
  "Shy",
  "Sickly",
  "Skeletal",
  "Skinny",
  "Sleek",
  "Sloppy",
  "Small eyes",
  "Smiling",
  "Smooth skin",
  "Snaggletooth",
  "Snazzy",
  "Sneering",
  "Snub nose",
  "Soft-spoken",
  "Solid",
  "Soothing voice",
  "Spectacled",
  "Spiky hair",
  "Spindly",
  "Spirited",
  "Square jaw",
  "Squat",
  "Stately",
  "Stocky",
  "Striking",
  "Stubbled",
  "Studious",
  "Stunning",
  "Stylish",
  "Sun-kissed skin",
  "Sunburned",
  "Supple",
  "Svelte",
  "Swaggering",
  "Sweaty",
  "Sweet",
  "Symmetrical",
  "Tall",
  "Tanned",
  "Tattoos",
  "Teasing",
  "Teeth gap",
  "Tense",
  "Thin",
  "Thinning hair",
  "Thick eyebrows",
  "Thick lips",
  "Thick-rimmed glasses",
  "Thoughtful",
  "Throaty voice",
  "Thunder thighs",
  "Tight-lipped",
  "Tiny",
  "Tired",
  "Toothy grin",
  "Tousled hair",
  "Towering"]


gold = [1000,3000,6000,10500,16000,23500,33000,46000,62000,82000,108000,140000,185000,240000,315000,410000,530000,685000,880000]

mannerisms = ['Adjusts glasses', 'Bites fingernails', 'Bites lip', 'Blows bubbles', 'Brushes hair out of face', 'Bursts into laughter', 'Chews gum', 'Chuckles', 'Clicks pen', 'Clutches purse tightly', 'Combs hair with fingers', 'Covers mouth when speaking', 'Cracks knuckles', 'Crosses arms', 'Crosses legs', 'Curls up in a ball', 'Doodles', 'Drums fingers', 'Eyes dart around room', 'Fiddles with hair', 'Fidgets', 'Flexes muscles', 'Folds arms', 'Furrows brow', 'Gestures while talking', 'Glances at watch', 'Grins', 'Hides hands in pockets', 'Hugs oneself', 'Hums to oneself', 'Jingles keys', 'Jumps up and down', 'Laughs at own jokes', 'Leans back', 'Leans forward', 'Licks lips', 'Lifts eyebrows', 'Lifts chin', 'Licks teeth', 'Looks around nervously', 'Looks over glasses', 'Mumbles', 'Nervously clears throat', 'Nods often', 'Opens and closes mouth', 'Paces', 'Pats pockets', 'Peers over glasses', 'Plays with jewelry', 'Plays with sleeves', 'Pops knuckles', 'Puts hands in pockets', 'Raises eyebrows', 'Readjusts clothing', 'Rests chin in hand', 'Rests hand on hip', 'Rests head on hand', 'Rolls eyes', 'Rub hands together', 'Runs fingers through hair', 'Scratches head', 'Shakes head', 'Shifts weight from one foot to the other', 'Shrugs', 'Sighs', 'Smacks lips', 'Smiles', 'Smirks', 'Snaps fingers', 'Squints', 'Stares into space', 'Stares intensely', 'Stifles a yawn', 'Strokes chin', 'Sways back and forth', 'Sweats', 'Swings arms', 'Taps foot', 'Taps pencil', 'Thumbs through a book', 'Throws head back when laughing', 'Tilts head', 'Tucks hair behind ears', 'Twiddles thumbs', 'Twirls hair', 'Twists hair', 'Twitches', 'Winks', 'Wipes hands on pants', 'Wipes nose', 'Wipes sweat from forehead', 'Withdraws into oneself', 'Wring hands', 'Yawns', 'Yells when excited', 'Zones out', 'Bites lower lip', 'Bites upper lip', 'Blows nose', 'Brushes off clothes', 'Clenches fists', 'Clenches jaw', 'Combs mustache', 'Covers ears', 'Covers eyes', 'Crosses fingers', 'Crouches', 'Cups chin with hand', 'Dabs at eyes', 'Dons sunglasses', 'Drops head', 'Elevates eyebrows', 'Exhales audibly', 'Fans oneself', 'Fiddles with jewelry', 'Fingers lapel', 'Flips hair', 'Folds hands', 'Gathers hair into a ponytail', 'Glances away', 'Glances over shoulder', 'Gnaws on pencil', 'Grits teeth', 'Holds breath', 'Huffs', 'Jumps at sudden sounds', 'Kicks at the ground', 'Kneads fingers', 'Kneels', 'Lays head on desk', 'Leans on desk', 'Lift']

#class specific choices
#ranger
favored_terrains = ['Cold', 'desert', 'Forest', 'Jungle', 'Mountain', 'Plains', 'Planes [choose]', 'Swamp', 'Underground', 'Urban', 'Water']
favored_enemies = ['Aberration', 'Animal', 'Construct', 'Dragon', 'Fey', 'Humanoid (aquatic)', 'Humanoid (dwarf)', 'Humanoid (elf)','Humanoid (giant)','Humanoid (goblinoid)', 'Humanoid (gnoll)', 'Humanoid (gnome)', 'Humanoid (halfling)','Humanoid (human)', 'Humanoid (orc)', 'Humanoid (reptilian)', 'Humanoid (other subtype)', 'Magical beast', 'Monstrous humanoid', 'Ooze', 'Outsider (air)', 'Outsider (chaotic)','Outsider (earth)', 'Outsider (evil)', 'Outsider (fire)', 'Outsider (good)', 'Outsider (lawful)', 'Outsider (native)', 'Outsider (water)', 'Plant', 'Undead', 'Vermin']

#rogue

#barbarian



#add all of forests options
traits = ['ambitious', 'anxious', 'artistic', 'brave', 'calm', 'careless','charming', 'clever', 'compassionate', 'confident', 'creative','curious', 'daring', 'dependable', 'determined', 'discreet','distrustful', 'eccentric', 'emotional', 'energetic', 'enthusiastic','ethical', 'excitable', 'friendly', 'frustrated', 'generous','gloomy', 'graceful', 'grateful', 'gregarious', 'guarded', 'happy','hardworking', 'honest', 'humorous', 'imaginative', 'impatient','indecisive', 'independent', 'industrious', 'inquisitive', 'intelligent','introverted', 'kind', 'knowledgeable', 'logical', 'loyal', 'mature','methodical', 'modest', 'moody', 'naive', 'narcissistic', 'neurotic','optimistic', 'organized', 'outgoing', 'paranoid', 'passionate', 'patient','perfectionist', 'persistent', 'pessimistic', 'philosophical', 'playful','polite', 'practical', 'proactive', 'proud', 'quiet', 'quick-tempered','rational', 'reliable', 'reserved', 'resourceful', 'restless', 'romantic','sensitive', 'serious', 'shy', 'skeptical', 'sociable', 'solitary','spontaneous', 'stubborn', 'studious', 'submissive', 'suspicious','talkative', 'temperamental', 'thoughtful', 'thrifty', 'tolerant','trustworthy', 'unselfish', 'unstable', 'vain', 'virtuous', 'warmhearted','wary', 'witty', 
              'Adventurous', 'Affectionate', 'Aggressive', 'Analytical', 'Assertive', 'Cautious', 'Charismatic', 'Charming', 'Clever', 'Comical', 'Compassionate', 'Confident', 'Conservative', 'Considerate', 'Courageous', 'Cynical', 'Dependable', 'Determined', 'Devoted', 'Eccentric', 'Empathetic', 'Energetic', 'Enthusiastic', 'Excitable', 'Extroverted', 'Friendly', 'Gregarious', 'Hardworking', 'Idealistic', 'Innovative', 'Insightful', 'Intelligent', 'Intuitive', 'Inventive', 'Inquisitive', 'Jovial', 'Loyal', 'Meticulous', 'Mysterious', 'Objective', 'Observant', 'Optimistic', 'Organized', 'Outgoing', 'Passionate', 'Patient', 'Perfectionist', 'Persistent', 'Pessimistic', 'Practical', 'Protective', 'Rational', 'Realistic', 'Reliable', 'Reserved', 'Resourceful', 'Respectful', 'Responsible', 'Risk-taking', 'Romantic', 'Sarcastic', 'Skeptical', 'Sociable', 'Spontaneous', 'Stoic', 'Straightforward', 'Stubborn', 'Sympathetic', 'Tactful', 'Tenacious', 'Thoughtful', 'Trusting', 'Unconventional', 'Understanding', 'Unselfish', 'Vigilant', 'Visionary', 'Warm', 'Witty', 'Zealous']

#add all of forests options

# Comprehensive list of Archetypes:
#need to use archetypes_{class_name} so we can grab it like this later
                    #Base Classes


                    #Path of war classes

background_traits = ["Absolute Loyalty",
"Accelerated Drinker",
"Ambush Training",
"Anatomist",
"Armor Expert",
"Axe to Grind",
"Battlefield Disciple",
"Berserker of the Society",
"Black Powder Bravado",
"Black Powder Fortune",
"Black Powder Interjection",
"Blade of the Society",
"Bloodthirsty",
"Bullied",
"Careful Combatant",
"Coherent Rage",
"Cold and Calculating",
"Courageous",
"Crowd Dodger",
"Dedicated Defender",
"Defender of the Society",
"Deft Dodger",
"Demon Slayer",
"Demon Smiter",
"Dirty Fighter",
"Disillusioned",
"Dispelled Battler",
"Dueling Cloak Adept",
"Easy Way or the Hard Way",
"Evasive Sting",
"Excitable",
"Faith's Hunter",
"Fencer",
"Firebug",
"Hard to Kill",
"Helpful",
"Hidden Hand",
"Hill Fighter",
"Holdout",
"Honored Fist of the Society",
"Hunter's Knack",
"Improvised Defense",
"Indelible Ire",
"Inspiring",
"Inspiring Rush",
"Jungle Fighter",
"Just Like New",
"Killer",
"Kin Guardian",
"Larger Than Life",
"Martial Performer",
"Muscle of the Society",
"natures Mimic",
"Never Stop Shooting",
"Pillager",
"Reactionary",
"Reckless",
"Reckless Contempt",
"Resilient",
"Resolve of the Rejected",
"River Fighter",
"Savanna Hunter",
"Scarred Descendant",
"Slippery",
"Soaring Sprinter",
"Sprint",
"Startling Report",
"Steel Skin",
"Strong Arm, Supple Wrist",
"Surprise Weapon",
"Sworn Enemy",
"Tactician",
"Threatening Defender",
"Tracker of the Society",
"Unblemished Barrel",
"Vengeful",
"Vigilant Battler",
"Weapon of Peace",
"Witty Repartee",
"Authoritarian",
"Beacon of Faith",
"Birthmark",
"Blessed",
"Blessed Touch",
"Called",
"Caretaker",
"Child of the Temple",
"Chosen One",
"Defy Madness",
"Devoted Healer",
"Devotee of the Green",
"Disdainful Defender",
"Ease of Faith",
"Exalted of the Society",
"Faithful Feedback",
"Fate's Favored",
"Fearless Defiance",
"First Memories",
"Focused Disciple",
"History of Heresy",
"Honest",
"Indomitable Faith",
"Inspired",
"Irrepressible",
"Loyalty across Lifetimes",
"Martial Manuscript",
"Mystery Initiate",
"Necrotic Aura",
"Oathbound",
"Omen",
"Patient Calm",
"Perpetual Companion",
"Planar Savant",
"Principled",
"Prophesied",
"Redeemer",
"Reincarnated",
"Sacred Conduit",
"Sacred Touch",
"Scholar of the Great Beyond",
"Schooled Inquisitor",
"Spell Intuition",
"Spirit Sense",
"Stalwart of the Society",
"Tireless Avenger",
"Unnatural Presence",
"Wanderer's Shroud",
"Zealot",
"Zealous Striker",
"Air-Touched",
"Alchemical Adept",
"Alchemical Intuition",
"Arcane Revitalization",
"Arcane Temper",
"Ascendant Recollection",
"Beast of the Society",
"Bladed Magic",
"Charlatan",
"Child of the Moon",
"Classically Schooled",
"Cross-Disciplined",
"Cross-Knowledge",
"Dangerously Curious",
"Deep Guardian",
"Desperate Resolve",
"Desperate Speed",
"Diabolical Dabbler",
"Distance Aptitude",
"Domineering",
"Earth-Touched",
"Earthbound",
"Eldritch Delver",
"Eldritch Smith",
"Enduring Mutagen",
"Fey Protection",
"Flame-Touched",
"Focused Burn",
"Focused Mind",
"Fortunate",
"Ghost Sight",
"Gifted Adept",
"Greater Adept of the Society",
"Greater Link",
"Greater Purpose",
"Havoc of the Society",
"Hedge Magician",
"Insistent Benefactor",
"Inured to Death",
"Keen Appraiser",
"Kin Bond",
"Knowledgeable Caster",
"Linked Surge",
"Lucid Dreamer",
"Magic Crafter",
"Magical Flair",
"Magical Knack",
"Magical Lineage",
"Magical Talent",
"Malleable Magic",
"Mathematical Prodigy",
"Meticulous Concoction",
"Mutant Eye",
"Naturally Gifted",
"Outcast's Intuition",
"Overwhelming Beauty",
"Partial Protege",
"Pathfinder's Focus",
"Perfectionist's Brew",
"Possessed",
"Pragmatic Activator",
"Precise Treatment",
"Reluctant Apprentice",
"Resilient Caster",
"Scorned by Magic",
"Second Tongue",
"Self-Taught Scholar",
"Shrouded Casting",
"Skeptic",
"Spark of Creation",
"Storm-Touched",
"Strength Foretold",
"Strength of the Land",
"Tenacious Shifting",
"Theoretical Magician",
"Transmuter",
"Trickster",
"Twinned Presence",
"Two-World Magic",
"Unscathed",
"Unseen but Not Undone",
"Unstable Mutagen",
"Volatile Conduit",
"Water-Touched",
"Acrobat",
"Adopted",
"Affable",
"Ambitious",
"Artisan",
"Avid Reader",
"Bastard",
"Beast Bond",
"Bruising Intellect",
"Bully",
"Calculated Bribe",
"Canter",
"Charming",
"Child of the Streets",
"Civilized",
"Clever Wordplay",
"Collector",
"Competitive",
"Contagious Mettle",
"Convincing Liar",
"Criminal",
"Cynical Ear",
"Destined Diplomat",
"Dismantle Order",
"Doublespeak",
"Enemy of Slavers",
"Etymologist",
"Explorer",
"Fast-Talker",
"Free Spirit",
"Friend in Every Town",
"Friends in High Places",
"Friends in Low Places",
"Gnomish Alchemist",
"Gregarious",
"Grief-Filled",
"Grim Optimism",
"Hardly a Fool",
"Harvester",
"Hell Knight Ancestry",
"Hunter's Blood",
"Imposing Scion",
"Influence",
"Knowing the Enemy",
"Law Enforcer",
"Life of Toil",
"Lost Nobility",
"Maestro of the Society",
"Mediator",
"Memorable",
"Mentored",
"Mercenary",
"Merchant",
"Natural-Born Leader",
"Noble Savage",
"Nonchalant Thuggery",
"Ordinary",
"Orphaned",
"Poverty-Stricken",
"Prince/Princess",
"Relic-Proof",
"Rest for the Wicked",
"Rich Parents",
"Savage",
"Savant",
"Secret-Keeper",
"Seeker",
"Signature Moves",
"Simple Disciple",
"Snowbound",
"Student of Philosophy",
"Style Sage",
"Supportive",
"Suspicious",
"Talented",
"Tireless Logic",
"Tropical Upbringing",
"Trustworthy",
"Truth's Agent",
"Unintentional Linguist",
"Unnatural Revenge",
"Unpredictable",
"Veiled Disciple",
"Wanderlust",
"Weathered Emissary",
"Without a Past",
"Worldly",
"Chance Savior",
"Inspired by Greatness",
"Making Good on Promises",
"On the Payroll",
"Subject of Study",
"Teacher’s Pet",
"Child of Infamy",
"Conspiracy Hunter",
"Diabolist Raised",
"Firebrand",
"Infernal Bastard",
"Shadow Child",
"The Pathfinder's Exile",
"Drug Addict",
"Framed",
"Love Lost",
"Missing Child",
"Unhappy Childhood",
"Best Friend",
"Caravan Guard",
"Childhood Crush",
"Foster Child",
"Friend of the Family",
"Hero Worship",
"Rescued",
"Student Survivalist",
"Younger Sibling",
"Bastard",
"Brigand",
"Issian",
"Noble Born",
"Pioneer",
"Riverlander",
"Sword Scion",
"Earning Your Freedom",
"Finding Your Kin",
"Gnoll Killer",
"Missionary",
"Reclaiming your Roots",
"Seeking Adventure",
"Blood of Pharaohs",
"Devotee of the Old Gods",
"Foreign Opportunist",
"Inquisitive Archaeologist",
"Mummy-Cursed",
"Necropolis Native",
"Resurrected",
"Sphinx Riddler",
"Trap Finder",
"Undead Crusader",
"Black Sheep",
"Favored Child",
"Outlander",
"Fools for Friends",
"Into Enemy Territory",
"Looking for Work",
"Optimistic Gambler",
"Researching the Blot",
"Scouting for Fiends",
"Boarded [A]",
"Boarded [B]",
"Boarded [C]",
"Boarded [D]",
"Colonial",
"Get the Cargo Through",
"Jungle Scholar",
"Ship's Crew",
"Stowaway",
"Alabaster Outcast",
"Exchange Agent",
"Former Assassin",
"Monument Scholar",
"Nontraditional Native",
"Ruin Raider",
"Serpent Runner",
"Ancient Explorer",
"Barroom Talespinner",
"Buccaneer's Blood",
"Dockside Brawler",
"Eye for Plunder",
"Native",
"Natural Born Sailor",
"Peg Leg",
"Ship's Surgeon",
"Touched by the Sea",
"Augmented Disguise",
"Dealmaker",
"Extremely Fashionable",
"Heirloom Weapon",
"Improvisational Equipment",
"Iron Liver",
"Power of Suggestion",
"Prehensile Whip",
"Quick Learner",
"Rough and Ready",
"Stage Magic",
"Stealthy Escape",
"Thrown-Together Fashion",
"A Sure Thing",
"Aid Allies",
"Attuned to the Ancestors",
"Bad Reputation",
"Beneficient Touch",
"Captain's Blade",
"Comparative Religion",
"Dervish",
"Desert Shadow",
"Devil's Mark",
"Dunewalker",
"Eastern Mysteries",
"Expert Duelist",
"Fashionable",
"Fiendish Presence",
"Fires of Hell",
"Force For Good",
"Fortified",
"Goldfinger",
"Greasy Palm",
"Horse Lord",
"Hunter's Eye",
"I Know a Guy",
"Impressive Presence",
"Indomitable",
"Insider Knowledge",
"Loyalty",
"Master of Pentacles",
"Medic",
"Meridian Strike",
"Meticulous Artisan",
"Mind Over Matter",
"Mummy-Touched",
"Observant",
"Performance Artist",
"Proper Training",
"Saint's Ward",
"Secrets of the Sphinx",
"Shadow Diplomat",
"Shiv",
"Sotto Voce",
"Soul-Drinker",
"Storyteller",
"Teaching Mistake",
"Tomb Raider",
"Trouper",
"Unorthodox Strategy",
"Vindictive",
"Watchdog",
"Weapon Style",
"Blood of Dragons",
"Deathtouched",
"Fiend Blood",
"Adaptable Flatterer",
"Adrift",
"Advantageous Distraction",
"Adventurous Explorer",
"Aerial Observer",
"Alchemical Breath",
"Almost Human",
"Animal Friend",
"Animalistic Affliction",
"Anticipate Evil",
"Arcane Dabbler",
"Arcane Student",
"Arms Master",
"Artistic Dilettante",
"Aspiring Bard",
"Assimilated Native",
"Auspicious Tattoo",
"Balloon Headed",
"Beast Bully",
"Bent Body",
"Big Boned",
"Big Ears",
"Blade Bravado",
"Blessing of Darkness",
"Blood Stalker",
"Boar Resilience",
"Bog Scamp",
"Born Damned",
"Born in the Light",
"Born to the Water",
"Bouncy",
"Bralani's Step",
"Bred for War",
"Brewmaster",
"Brute",
"Buried Anxiety",
"Burnished Skin",
"Caravan Drover",
"Carefully Hidden",
"Carnation Scales",
"Celestial Tracker",
"Centaur Vengeance",
"Chain Master",
"Child of Platinum",
"Clearheaded",
"Clergy Member",
"Cold Fortitude",
"Colonial Entitlement",
"Colonial Sympathizer",
"Color Thief",
"Creative Manipulator",
"Crocodile Swim",
"Curse in the Blood",
"Dark Magic Affinity",
"Deadly Rush",
"Death’s Deputy",
"Deathkeeper",
"Deep Marker",
"Dilettante Artist",
"Dog-Sniff-Hate",
"Dowsing",
"Draconic Echo",
"Durable Change",
"Elaborate Trapper",
"Elven Reflexes",
"Elven Serenity",
"Enlightened Warrior",
"Ethical Leader",
"Ever Home",
"Ever Wary",
"Eyes of the Sun",
"Failed Apprentice",
"Faith Healer",
"Family Connections",
"Fanatic",
"Fanatic",
"Feline Instinct",
"Fiery Glare",
"Fight with the Flock",
"Final Embrace",
"Finish the Fight",
"Fire-Tongued",
"Firebug",
"Flair for Destruction",
"Following Breeze",
"Forlorn",
"Foul Belch",
"Freed Slave",
"Freedom Fighter",
"Freedom Fighter",
"Friendless",
"Frost Spitter",
"Genie Blood",
"Glib Barrister",
"Goblin Foolhardiness",
"God Scorn",
"Golden Scales",
"Goldsniffer",
"Good Influence",
"Grounded",
"Half-Forgotten Secrets",
"Harrow Born",
"Harrow Chosen",
"Heat Fortitude",
"Helpful",
"Historian",
"Horse Lord",
"Ice Walker",
"Icy Mementos",
"Inciter",
"Infernal Influence",
"Inheritor",
"Inheritor",
"Innocent",
"Inured to Disease",
"Iron Control",
"Keeper of the Ancestral Scrolls",
"Kobold Faith",
"Kobold Herbalist",
"Lantern Spirit",
"Latent Psion",
"Legacy of Sand",
"Lettered",
"Lightning-Blessed",
"Lillend's Harp",
"Linguistic Genius",
"Liquid-Tongued",
"Lycanthropic Bloodlust",
"Market Rat",
"Martyr's Blood",
"Master of the Sudden Strike",
"Masterful Demeanor",
"Mastery of Form",
"Militant Merchant",
"Mind Trapper",
"Motherless",
"Nomadic",
"Numerological Gift",
"Old Before Your Time",
"Ooze Defense",
"Open Hand and Mind",
"Operatic",
"Outcast",
"PAGE MISSING",
"Pain Artist",
"Pearl Diver",
"Perfect Servant",
"Planar Negotiator",
"Planetar's Visions",
"Practiced Impression",
"Prayer Breaker",
"Precision Hearing",
"Pride of the Diamond Empire",
"Prideful Temper",
"Prolong Magic",
"Proud Tribesman",
"Providential Passenger",
"Purple Scales",
"Pustular",
"Pyromancer",
"Rapscallion",
"Rat Squeeze",
"Relic Hunter",
"Repel Sin",
"Repulsive",
"Reviving Rest",
"Rude Songs",
"Ruthless",
"Sandy Ambush",
"Scholar of Ruins",
"Scrapper",
"Scrounger",
"Seeker of Brightness",
"Selective Health",
"Sensual Graces",
"Shadow Stabber",
"Shared Curse",
"Sharkchild",
"Shield Bearer",
"Shift the Blame",
"Shoreline Skirmisher",
"Skater's Balance",
"Slave Smuggler",
"Slaver",
"Slippery Step",
"Slithering Stride",
"Smoke Resistant",
"Snake Hater",
"Snap Ignition",
"Sneaky Swimmer",
"Soul Eater",
"Speech of the Wilds",
"Sphinxfriend",
"Spirits in the Stone",
"Stargazer",
"Stoic Dignity",
"Strength of Body",
"Successful Shirker",
"Suicidal",
"Superior Clutch",
"Superstitious",
"Tattooed Mystic",
"Tempter's Tongue",
"Terrifying Lunge",
"Thoroughbred",
"Thrall Spotter",
"Tiger's Claw",
"Tongue of Many Towns",
"Tough Skin",
"Toxophilite",
"Trade Talk",
"Trailblazer",
"Traumatic Shift",
"Trifler",
"Tropical Botanist",
"Tunnel Fighter",
"Twilight Zeal",
"Ugly Swine",
"Undead Slayer",
"Underling",
"Undine Loyalty",
"Unearth Secrets",
"Unidentifiable Appeal",
"Vermin Wrangler",
"Vile Kiss",
"Voice of Velvet",
"Warrior of Old",
"Warsmith",
"Wary",
"Well-Informed",
"World Traveler",
"Youthful Mischief",
"Zest for Battle",
"Aberration Hunter",
"Acupuncturist",
"Addicted",
"Advocate for the Empire",
"Alchemical Prodigy1",
"Alchemical Prodigy2",
"Alien Origins",
"Altruistic Diplomat",
"Antiquities Smuggler",
"Arbiter",
"Arcane Dabbler",
"Arcane Graduate",
"Archeologist",
"Armor Master",
"Artifact Hunter",
"Aspiring Hell Knight",
"Bandit",
"Blood Steed",
"Blooded",
"Border Guard",
"Born Rider",
"Bounty Hunter",
"Brave",
"Briar Bandit",
"Builder's Apprentice",
"Candidate for Perfection",
"Cavalry Rider",
"Charger",
"Cheap to Feed",
"Child of the Crusades",
"Chivalrous",
"Chosen Child",
"City Defender",
"Clan Artisan",
"Cliff Jumper",
"Cliff-Master",
"Clumsy Slave",
"Coin Hoarder",
"Coincunning",
"Cold Heart",
"Community-Minded",
"Confidante to the Oppressed",
"Conscientious Miner",
"Construct Crafter",
"Cosmopolitan",
"Crusader Tactician",
"Cynic",
"Cypher Resistance",
"Darklands Delver",
"Dealer1",
"Dealer2",
"Demon Eradicator",
"Demon Slayer",
"Desert Child",
"Desert Nomad",
"Destined For Greatness",
"Devotee of the Holy Prophecies",
"Dim Seer",
"Diplomat",
"Disbeliever1",
"Disbeliever2",
"Discerning Beliefs",
"Disease Resistant",
"Diver",
"Dominator",
"Draconic Vigil",
"Dump Salvager",
"Dungeon Dweller",
"Dusk Agent",
"Dusk Agent",
"Dusk Dancer",
"Elemental Pupil",
"Emissary",
"Enemy of the Dead",
"Equality for All",
"Expert Smuggler",
"Eye of the Falcon",
"Famed Performer",
"Fixer",
"Flotsam",
"Freed Slave1",
"Freed Slave2",
"Freedom Fighter",
"Freedom Fighter",
"Freedom Fighter",
"Friend of the Dead",
"Friend of the Fey",
"Frontier-Forged",
"Frostborn",
"Gallant Imposter",
"Gatekeeper",
"Genie-Caller",
"Glory of Old",
"Gravelwalker",
"Great Market Merchant",
"Grit Goggles",
"Group Fighter",
"Guerilla",
"Guide of the Streets",
"Heart of Clay",
"Heavenly Touch",
"Heavy Hitter",
"Highlander",
"Hobgoblin Slayer",
"Honeyed Tongue",
"Humble Beginnings",
"Hunter of Outsiders",
"Imperial Soldier",
"Inspiring Speaker",
"Instigator of Rebellion",
"Iron Lungs",
"Iron Mind",
"Jungle Guide",
"Jungle Walker",
"Kami Talker",
"Keeper of the Veil",
"Knowledgeable Citizen",
"Knowledgeable Citizen",
"Lair Snake",
"Left Behind",
"Lesser Noble",
"Lightning Rider",
"Local Know-It-All",
"Long Jumper",
"Lost Role Model",
"Lucky Turnabout",
"Mammoth Master",
"Master Illusionist",
"Master of Peaks",
"Merchant’s Child",
"Militia Veteran",
"Miner",
"Mordant Heritage",
"Mountain Guide",
"Natural Artist",
"Natural Climber",
"Navigator",
"Noble",
"Numerologist",
"On Guard",
"Open-Minded Explorer",
"Orc Impaler",
"Orphan",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"Paragon of Speed",
"Pearl Diver",
"Perseverance",
"Pirate",
"Pirate2",
"Plainsman",
"Pomp and Pageantry",
"Powerful Bloodline",
"Precocious Spellcaster",
"Privileged Slave",
"Prospector",
"Purchased Loyalty",
"Pure Legion Recruit",
"Quick Reactor",
"Rabble Rebel",
"Rebel Leader",
"Reformed Acolyte",
"Region's Finest",
"Regional Influence",
"Regional Recluse",
"Resilient",
"Resolute",
"Rice Runner",
"River Rat",
"Riverfolk",
"Savage Breaker",
"Savannah Child",
"Sea-Souled",
"Seafarer",
"Seasoned Climber",
"Secret Cultist",
"Shadowcaster",
"Signaler",
"Signature Spell",
"Silent Hunter",
"Silent Watcher",
"Silvertongued",
"Sky Spirit Worshiper",
"Slayer of the Deep",
"Smuggler",
"Snake Bleeder",
"Snowstride",
"Soldier of the Faith",
"Sound of Mind",
"Spell Duel Prodigy",
"Spellpiercer",
"Spiritual Forester",
"Stable",
"Storm Hunter",
"Stormrunner",
"Stream Nomad",
"Suck In Your Gut",
"Sun Orchid Harvester",
"Superstitious",
"Superstitious Ward",
"Surface Stranger",
"Survivalist",
"Survivalist",
"Survivor",
"Swamp Rebel",
"Swamp Survivor",
"Swordsman's Page",
"Talented Blacksmith",
"Tattooed Wanderer",
"Tattooed Wanderer",
"Technic Tinkerer",
"Temple Guard",
"Tiger Brigadier",
"Touched of the Gods",
"Town Gossip",
"Trained Medic",
"Trap Savvy",
"Traveling Merchant",
"Tribesman",
"True Believer",
"Tundra Child",
"Underworld Explorer",
"Urchin",
"Vagabond Child",
"Veteran Jungle Guide",
"Viking Blood",
"Walking Ward",
"Warrior Poet",
"Wastes Explorer",
"Wayang Spellhunter",
"Well Bred",
"Wharf Rat",
"Whole-Hearted",
"Winter Warrior",
"Winter’s Soul",
"Woodland Diplomat",
"A Shining Beacon",
"Affinity of the Elements",
"Agent of Chance",
"Alluring",
"Ambassador",
"Arcane Depth",
"Backstabber",
"Battlefield Caster",
"Battlefield Surgeon",
"Blade of Mercy",
"Blessing of the Feast",
"Broken Mind",
"Call for Help",
"Centered",
"Child of Nature",
"Cleansing Light",
"Cleansing the Twisted",
"Contract Master",
"Corpse Cannibal",
"Corpse Hunter",
"Courtesan",
"Dawn Renewal",
"Deathspeaker",
"Deck Fighter",
"Defensive Strategist",
"Deformed",
"Demon Hunter",
"Demonic Persuasion",
"Destructive Blows",
"Devotee of a Dead God",
"Divine Warrior",
"Ear for Music",
"Elven Pantheist",
"Empty Heart, Full Heart",
"Empyreal Focus",
"Eye of the Father",
"Eyes and Ears of the City",
"Eyes of the Wild",
"Faithful Artist",
"Faithful of the Dead God",
"Fatal Trapper",
"Fiendish Confidence",
"Flame of the Dawn",
"Flounderer",
"Fortified Drinker",
"Good Dreams",
"Good Natured",
"Guardian of the Forge",
"Hatred of the Gods",
"Holy Schemer",
"Honey-Tongued",
"Honeyed Words",
"Illuminator",
"Inner Beauty",
"Inoculated",
"Intense Artist",
"Iron Grip",
"Know the Land",
"Loreseeker",
"Lover of the Law",
"Magic is Life",
"Mother's Rage",
"Mother’s Teeth",
"Nimble Fingers, Keen Mind",
"Opener of Doors",
"Opportunistic",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"Pain Is Pleasure",
"Pantheist",
"Patient Optimist",
"Peacemaker",
"Potent Concoctions",
"Practiced Deception",
"Propitiation",
"Provider",
"Purity of Faith",
"Resigned",
"Restless Hunger",
"River Freedom",
"Sacred Avenger",
"Sacred Smasher",
"Scaly Ally",
"Searing Beacon",
"Second Chance",
"Secret Knowledge",
"Seer of Reality",
"Self-Sacrifice",
"Sense of Order",
"Sensing Imperfection",
"Serpentine Squeeze",
"Shadow Caster",
"Shadow Whispers",
"Spirit Guide",
"Spirit Talker",
"Starchild",
"Stoic Optimism",
"Strength of the Barghest",
"Strength of the Sun",
"Strip the Veils",
"Strong Heart",
"Strong Swimmer",
"Strong Willed",
"Talented Organizer",
"The City Protects",
"The Flexing Arm",
"Toilcrafter",
"Undead Slayer",
"Under Siege",
"Underlying Principals",
"Unhinged Mentality",
"Unspeakable Bond",
"Venom-Drenched",
"Veteran of Battle",
"Vindictive Strike",
"Voice of Monsters",
"Wasp Whisperer",
"Wisdom in the Flesh",
"Wise Teacher",
"Wolf Cub",
"Boarded [E]",
"Marked by Unknown Forces",
"No Escape",
"Unpredictable Reactions",
"Balancer's Banishing",
"Unabashed Gall",
"Amiable Blunder",
"Inexorable Authority",
"Elemental Endowment",
"Justiciar",
"Commercial Savvy",
"Evident Supporter",
"",
"Corpse Dodger",
"Child of the Necropolis",
"Unflinching Faith",
"Ghost Survivor",
"Ghoulish Affinity",
"Forbidden Knowledge",
"Holy Tattoo",
"Exiled Scholar",
"Alabaster Odalisque",
"Storm Pilot",
"Deepsea Native",
"Planar Scholar (Plane of Air)",
"Airship Captain (Plane of Air)",
"Channel the Earth (Plane of Earth)",
"Agent of the Sultana (Plane of Earth)",
"Solidarity (City of Brass)",
"Betrayed Ex-Noble (City of Brass)",
"Planar Historian (Plane of Water)",
"Aquatic Survivalist (Plane of Water)",
"Thoughtful Wish-Maker (Plane of Fire)",
"Fiery Dominance (Plane of Fire)",
"Whiteout (Undine)",
"Marid's Fury (Undine)",
"Wind-Carried Voices (Sylph)",
"Thunderborn (Sylph)",
"Instant Friendship (Suli)",
"Dualborn (Suli)",
"Statuesque (Oread)",
"Unflappable Arrogance (Ifrit)",
"Earthsense (Oread)",
"Expert Distractor (Ifrit)",
"Light Sleeper",
"Alchemists Apprentice",
"Detect Disobedience",
"Passionate Inertia",
"Subjective Truth",
"Wicked Leader",
"Bloody-Minded",
"Punish Insurrection",
"Horrifying Mind",
"Divine Deceiver",
"Obsequious Morsel",
"Shadowsight",
"Wardbreaker",
"Alert",
"Cooperative Combatant",
"Born under the Stranger",
"Awakened from Stasis",
"Scarred by Space Pirates",
"Lunar Birth ",
"Sun-Blessed ",
"Cellular Match",
"Nanite Revival",
"Adroit",
"Spidery Climber ",
"Skilled Telepath",
"Tactile Telekinesis",
"Transitional",
"Triaxian Dragonslayer ",
"Persuasive",
"Aballonian Resilience",
"Born under the Green Star",
"Eoxian Experiment",
"Triaxian Tradition",
"Akitonian Ferocity",
"Void Child",
"Skymetal Affinity",
"Offspring of the Ascension",
"Self-Reliant"]

professions = [ 
    "Priest",
    "Monk",
    "Nun",
    "Scribe",
    "Blacksmith",
    "Armorer",
    "Fletcher",
    "Carpenter",
    "Mason",
    "Weaver",
    "Beekeeper",
    "Falconer",
    "Furrier",
    "Baker",
    "Brewer",
    "Butcher",
    "Cheesemaker",
    "Fishmonger",
    "Miller",
    "Winemaker",
    "Tailor",
    "Shoemaker",
    "Tanner",
    "Potter",
    "Glassblower",
    "Jeweler",
    "Silversmith",
    "Bookbinder",
    "Papermaker",
    "printer",
    "Apothecary",
    "Physician",
    "Surgeon",
    "Barber",
    "Dentist",
    "Saddler",
    "Farrier",
    "Cartwright",
    "Shipwright",
    "Navigator",
    "Mercenary",
    "Soldier",
    "Guard",
    "Knight",
    "Nobleman",
    "Lady-in-waiting",
    "Squire",
    "Herald",
    "Minstrel",
    "Jester",
    "Fool",
    "Piper",
    "Street performer",
    "Actor",
    "Dancer",
    "Circus performer",
    "Tumbler",
    "Acrobat",
    "Fire-eater",
    "Juggler",
    "Clown",
    "Magician",
    "Fortune teller",
    "Witch",
    "Wizard",
    "Alchemist",
    "Herbalist",
    "Soothsayer",
    "Astrologer",
    "Cartographer",
    "Geographer",
    "Mathematician",
    "Philosopher",
    "Theologian",
    "Scholar",
    "Historian",
    "Chronicler",
    "Archivist",
    "Curator",
    "Librarian",
    "Bishop",
    "Cardinal",
    "Pope",
    "Inquisitor",
    "Monastic leader",
    "Abbott",
    "Prior",
    "Mother superior",
    "Abess",
    "Master of arms",
    "Huntsman",
    "Tracker",
    "Trapper",
    "Horse trainer",
    "Falconry trainer",
    "Dog trainer",
    "Master of hounds",
    "Forester",
    "Gamekeeper",
    "Woodsman",
    "Ranger",
    "Explorer",
    "Merchant",
    "Trader",
    "Banker",
    "Moneylender",
    "Accountant",
    "Burgomaster",
    "Mayor",
    "Town crier",
    "Town guard",
    "Constable",
    "Watchman",
    "Jailor",
    "Executioner",
    "Thief",
    "Burglar",
    "Assassin",
    "Spy",
    "Smuggler",
    "Pirate",
    "Corsair",
    "Privateer",
    "Torturer",
    "Interrogator",
    "Executioner's assistant",
    "Cult leader",
    "Heretic",
    "Blasphemer",
    "Witch hunter",
    "Demonologist",
    "Occultist",
    "Necromancer",
    "Medium",
    "Spiritualist",
    "Psychic",
    "Exorcist",
    "Ghost",
    "Executioner",
    "Inquisitor",
    "Scribe",
    "Barrister",
    "Courtier",
    "Falconer",
    "Tanner",
    "Farrier",
    "Potter",
    "Vintner",
    "Weaver",
    "Chandler",
    "Miller",
    "Baker",
    "Fisherman",
    "Sailor",
    "Navigator",
    "Cartographer",
    "Apothecary",
    "Herbalist",
    "Alchemist",
    "Astrologer",
    "Blacksmith",
    "Armorer",
    "Weaponsmith",
    "Bowyer",
    "Saddler",
    "Leatherworker",
    "Tailor",
    "Linen weaver",
    "Silk weaver",
    "Embroiderer",
    "Bookbinder",
    "Illuminator",
    "Jeweler",
    "Goldsmith",
    "Silvermith",
    "Carpenter",
    "Mason",
    "Plasterer",
    "Roofer",
    "Glassblower",
    "printer",
    "Bookkeeper",
    "Banker",
    "Moneylender",
    "Merchant",
    "Trader",
    "Shipwright",
    "Navigator",
    "Cartographer",
    "Miner",
    "Stonecutter",
    "Bricklayer",
    "Stonemason",
    "Quarryman",
    "Chimneysweep",
    "Plumber",
    "Well-digger",
    "Landscaper",
    "Gardener",
    "Farmer",
    "Orchardist",
    "Brewer",
    "Distiller",
    "Winegrower",
    "Horse trainer",
    "Jockey",
    "Falconer",
    "Hawker",
    "Furrier",
    "Taxidermist",
    "Gamekeeper",
    "Hunter",
    "Fisher",
    "Trapper",
    "Bard",
    "Minstrel",
    "Troubadour",
    "Jester",
    "Actor",
    "Playwright",
    "Dancer",
    "Acrobat",
    "Fire-eater",
    "Knife thrower",
    "Tightrope walker",
    "Contortionist",
    "Clown",
    "Magician",
    "Illusionist",
    "Sorcerer",
    "Witch",
    "Wizard",
    "Necromancer",
    "Summoner",
    "Conjurer",
    "Enchanter",
    "Hermit",
    "Monk",
    "Nun",
    "Friar",
    "Cleric",
    "Priest",
    "Bishop",
    "Cardinal",
    "Pope",
    "Perfumer",    "Glassblower",    "Weaver",    "Potter",    "Tinker",    "Cooper",    "Fencer",    "Falconer",    "Innkeeper",    "Soapmaker",    "Groom",    "Goldsmith",    "Charcoal Maker",    "printer",    "Armorer",    "Beekeeper",    "Herbalist",    "Locksmith",    "Cobbler",    "Furrier",    "Hatter",    "Saddler",    "Tailor",    "Launderer",    "Blacksmith",    "Candlemaker",    "Cook",    "Baker",    "Butcher",    "Cheesemaker",    "Brewer",    "Vintner",    "Apothecary",    "Barber",    "Basket Weaver",    "Boatbuilder",    "Bookbinder",    "Brewster",    "Bricklayer",    "Carpenter",    "Cartographer",    "Chandler",    "Clockmaker",    "Compass Maker",    "Cooper",    "Cutler",    "Dyer",    "Engraver",    "Farrier",    "Fletcher",    "Gemcutter",    "Glazier",    "Glovemaker",    "Grain Miller",    "Harness Maker",    "Hatter",    "Horner",    "Illuminator",    "Jeweler",    "Leatherworker",    "Luthier",    "Mason",    "Metalworker",    "Milliner",    "Musician",    "Painter",    "Parchment Maker",    "Plumber",    "Rope Maker",    "Sculptor",    "Siegemaster",    "Silversmith",    "Spice Merchant",    "Stonemason",    "Tanner",    "Tax Collector",    "Textile Merchant",    "Toolmaker",    "Vellum Maker",    "Weaponsmith",    "Whitesmith",    "Wine Merchant",    "Woodcarver",    "Woodwright",    "Wool Merchant",    "Writer",    "Zincworker",    "Glassmaker",    "Book Seller",    "Map Maker",    "Thatcher",    "Jester",    "Astrologer",    "Alchemist",    "Bailiff",    "Chaplain",    "Cook",    "Falconer",    "Ferryman",    "Ghost",    "Gongfarmer",    "Gravedigger",    "Guide",    "Hedge Witch",    "Herbalist",    "Hunter",    "Jailer",    "Knight",    "Mercenary",    "Miller",    "Miner",    "Monk",    "Nun",    "Noble",    "Pilgrim",    "Pirate",    "Poacher",    "Prostitute",    "Ranger",    "Sailor",    "Scribe",    "Slave",    "Soldier",    "Tinker",    "Trapper",    "Urchin",    "Wanderer",    "Witch",    "Wizard",
    "Embroiderer", "Herbalist",
    "Scabbard Maker", "Chandler",
    "Candle Maker", "Lamp Lighter",
    "Locksmith", "Wagon Maker",
    "Plasterer", "Saddle Maker",
    "Tile Layer", "Paper Maker",
    "Alchemist", "Rug Maker",
    "Bookbinder", "Paper Cutter",
    "Paper Marbler", "Parchment Maker",
    "Book printer", "Ink Maker",
    "Quill Cutter", "Scribe",
    "Black Powder Maker", "Falconer",
"Crochet Maker", "Weaver",
"Carpenter", "Barber",
"Surgeon", "Apothecary",
"Mason", "Butcher",
"Tinsmith", "Goldsmith",
"Silversmith", "Coppersmith",
"Brick Maker", "Pewterer",
"Glazier", "Glass Blower",
"Glass Etcher", "Stained Glass Maker",
"Loom Weaver", "Spinner",
"Sail Maker", "Nail Maker",
"Lock Maker", "Screw Maker",
"Pin Maker", "Needle Maker",
"Rope Maker", "Net Maker",
"Quilt Maker", "Blanket Maker",
"Carpet Maker", "Dyer",
"Shoemaker", "Cobbler",
"Leatherworker", "Harness Maker",
"Saddle Maker", "Tanner",
"Farrier", "Stable Hand",
"Jockey", "Horse Trainer",
"Cartographer", "Map Maker",
"Navigator", "Shipwright",
"Ship Captain", "Seaman",
"Fisherman", "Whaler",
"Seal Hunter", "Oil Maker",
"Rope Sailor", "Marine Painter",
"Net Sailor", "Seashell Collector",
"Sea Sponge Hunter", "Pearl Diver",
"Rigger", "Navigator's Assistant",
"Chirurgeon", "Alewife",
"Barkeep", "Brewer",
"Distiller", "Vintner",
"Winemaker", "Cheesemaker",
"Butter Maker", "Milkmaid",
"Chandler", "Candle Maker",
"Lamp Lighter", "Lantern Maker",
"Papermaker", "Bookbinder",
"Bookseller", "Clerk",
"Librarian", "School Teacher",
"Professor", "Astronomer",
"Cartwright", "Cooper",
"Gunsmith", "Arquebusier",
"Crossbowman", "Longbowman",
"Javelin Thrower", "Knife Thrower",
"Slinger", "Archer",
"Crossbow Maker", "Longbow Maker",
"Spear Maker", "Pike Maker",
"Bladesmith", "Knifemaker",
"Axe Maker", "Sword Maker",
"Mace Maker", "Flail Maker",
"Halberd Maker", "Blacksmith",
"Armorer", "Metal Worker",
"Bronze Worker", "Copper Worker",
"Iron Worker", "Steel Worker",
"Chain Maker", "Scale Maker",
"Helm Maker", "Shield Maker",
"Plate Mail Maker", "Chain Mail Maker",
"Leather Armor Maker", "Arrow Maker",
"Bolt Maker", "Quartermaster",
"Scout", "Tracker",
"Mercenary", "Poacher",
"Outlaw", "Bandit",
"Highwayman", "Pirate",
"Smuggler", "Spy",
"Tinkerer",
"Grave Robber",
"Shipwright",
"Scavenger",
"Ice Fisherman",
"Scribe",
"Beekeeper",
"Weaver",
"Grocer",
"Diplomat",
"Astrologer",
"Candle Maker",
"Glassblower",
"Lighthouse Keeper",
"Water Carrier",
"Dyer",
"Falconer",
"Locksmith",
"Engraver",
"Jester",
"Rat Catcher",
"Wagon Maker",
"Spice Merchant",
"Saddle Maker",
"Furrier",
"Vintner",
"Miner",
"Chandler",
"Gardener",
"Cartographer",
"Herbalist",
"Horse Breeder",
"Thatcher",
"Weapon Smith",
"Jeweler",
"Metalworker",
"Leatherworker",
"Fisherman",
"Map Maker",
"Baker",
"Mason",
"Potter",
"Tailor",
"Carpenter",
"Painter",
"Butcher",
"Ship Captain",
"Alchemist",
"Tavern Keeper",
"Mercenary",
"Wealthy Merchant",
"Wood Carver",
"Sail Maker",
"Sculptor",
"Barber",
"Clockmaker",
"Embroiderer",
"Fletcher",
"Gilder",
"Hatter",
"Herald",
"Innkeeper",
"Illuminator",
"Lapidary",
"Mercer",
"Paper Maker",
"Parchment Maker",
"Pewterer",
"Rope Maker",
"Saddler",
"Siege Engineer",
"Silversmith",
"Stone Mason",
"Tapestry Maker",
"Tax Collector",
"Tent Maker",
"Toll Keeper",
"Toymaker",
"Trapper",
"Vestment Maker",
"Vicar",
"Water Mill Operator",
"Weigh Master",
"Whaler",
"Wood Turner",
"Brewer",
"Mead Maker",
"Oil Maker",
"Honey Gatherer",
"Bookbinder",
"Furniture Maker",
"Gem Cutter",
"Grain Miller",
"Groom",
"Irrigation Specialist",
"Marble Cutter",
"Roofer",
"Sash and Door Maker",
"Scribe",
"Ship's Carpenter",
"Tinsmith",
"Torturer",
"Urchin",
"Wax Chandler",
"Mapmaker",
"Vintner",
"Weaver",
"Winemaker",
"Cooper",
"Fletcher",
"Herbalist",
"Innkeeper",
"Shipwright",
"Barrister",
"Limner",
"Sailmaker",
"Armorer",
"Astrologer",
"Sculptor",
"Tapestry Maker",
"Jester",
"Pursemaker",
"Gilder",
"Bowyer",
"Locksmith",
"Tiler",
"Parchment Maker",
"Ropemaker",
"Tattoo Artist",
"Rug Maker",
"Furrier",
"Horn Carver",
"Shoemaker",
"Pewterer",
"Brewer",
"Woodcarver",
"Baker",
"Wainwright",
"Glassblower",
"Silversmith",
"Wine Merchant",
"Chandler",
"Mason",
"Bellmaker",
"Farrier",
"Shipbuilder",
"Parchmenter",
"Leatherworker",
"Ironmonger",
"Bookbinder",
"Apothecary",
"Saddle Maker",
"Swordsmith",
"Gemcutter",
"Soapmaker",
"Hatter",
"Embroiderer",
"Hedge Layer",
"Basket Maker",
"Falconer",
"Tinsmith",
"Wheelwright",
"Stonecutter",
"Mintmaster",
"Plasterer",
"Rope Spinner",
"Tavern Keeper",
"Cook",
"Blacksmith",
"Jeweler",
"Lapidary",
"Carpenter",
"Cheesemaker",
"Armorer",
"Coiner",
"Ship Captain",
"Dyer",
"Luthier",
"Saddler",
"Candlemaker",
"Perfumer",
"Fishmonger",
"Woodturner",
"Potter",
"Tanner",
"Spice Merchant",
"Tailor",
"Brushmaker",
"Metalworker",
"Cobbler",
"Fence Maker",
"Scribe",
"Cooper",
"Clockmaker",
"Paint Maker",
"Caster",
"Engraver",
"Furniture Maker",
"Goldsmith",
"Papermaker",
"Lampmaker",
"Loom Weaver",
"Millwright",
"Nailsmith",
"Stone Carver",
"Weaver",
"Wool Dyer",
"Zookeeper", "Horse Trainer", "Aquarist", "Wildlife Biologist", "Animal Behaviorist", "Zoologist", "Herpetologist", "Marine Biologist", "Animal Nutritionist", "Equine Dentist", "Vet Technician", "Animal Control Officer", "Animal Chiropractor", "Avian Veterinarian", "Pet Groomer", "Pet Store Manager", "Livestock Inspector", "Fish and Game Warden", "Pet Photographer", "Pet Behaviorist", "Wildlife Rehabilitator", "Pet Adoption Counselor", "Dolphin Trainer", "Pet Sitter", "Canine Massage Therapist", "Animal Shelter Manager", "Horse Breeder", "Animal Trainer", "Rabbit Breeder", "Falconer", "Equestrian Coach", "Horse Farrier", "Animal Welfare Advocate", "Pet Retail Salesperson", "Wildlife Conservationist", "Animal Communicator", "Horse Riding Instructor", "Pet Waste Removal Specialist", "Pet Supply Store Owner", "Pet Adoption Coordinator", "Dog Walker", "Pet Insurance Agent", "Pet Transportation Specialist", "Zoo Curator", "Animal Physical Therapist", "Aquatic Veterinarian", "Pet Portrait Artist", "Pet Funeral Director", "Animal Massage Therapist", "Llama Trainer", "Animal Care Technician", "Pet First Aid Instructor", "Guide Dog Trainer", "Animal Geneticist", "Animal Nutrition Consultant", "Bird Keeper", "Animal Rights Activist", "Animal Pathologist", "Pet Nutritionist", "Fish Farmer", "Animal Acupuncturist", "Pet Bakery Owner", "Zookeeper Educator", "Pet Boutique Owner", "Petting Zoo Attendant", "Wildlife Photographer", "Dog Daycare Owner", "Animal Show Host", "Pet Product Designer", "Exotic Animal Handler", "Animal Artist", "Rodeo Clown", "Horse Whisperer", "Pet Massage Therapist", "Wildlife Educator", "Horse Racing Official", "Zoo Veterinarian", "Pet Product Tester", "Animal Cognition Researcher", "Pet Waste Composting Specialist", "Aquatic Animal Trainer", "Animal Forensic Specialist", "Pest Control Technician", "Animal Husbandry Expert", "Animal Sanctuary Manager", "Pet CPR Instructor", "Animal Shelter Volunteer Coordinator", "Canine Nutritionist", "Pet Boutique Manager", "Fishery Manager", "Petting Zoo Owner", "Livestock Auctioneer", "Zoo Maintenance Worker", "Pet Loss Grief Counselor", "Horse Riding Camp Instructor", "Wildlife Habitat Specialist", "Animal Casting Agent",
"Bookbinder", "Candlemaker", "Clockmaker", "Cooper", "Engraver", "Featherworker", "Fletching", "Florist", "Gloversmith", "Hatter", "Horologist", "Inlay Maker", "Jeweler", "Knifemaker", "Luthier", "Mandolin Maker", "Miniaturist", "Netmaker", "Optician", "Perfumer", "Quilter", "Roofer", "Saddler", "Scrimshaw Artist", "Shipwright", "Silversmith", "Spinning Wheel Maker", "Stained Glass Artist", "Stonemason", "Tailor", "Teddy Bear Maker", "Thatching", "Tilemaker", "Toymaker", "Upholsterer", "Weaver", "Whipmaker", "Wicker Worker", "Wigmaker", "Woodcarver", "Woodworker", "Basket Weaver", "Belt Maker", "Bead Weaver", "Bladesmith", "Bowmaker", "Brickmaker", "Cabinetmaker", "Calligrapher", "Ceramist", "Chairmaker", "Chaser", "Chocolatier", "Cobbler", "Cosmetics Maker", "Costume Designer", "Cotton Gin Maker", "Crocheter", "Dollmaker", "Embroiderer", "Fan Maker", "Glassblower", "Goldsmith", "Hatmaker", "Hayrake Maker", "Instrument Maker", "Ironmonger", "Kite Maker", "Lace Maker", "Lapidary", "Leatherworker", "Loom Builder", "Marbleworker", "Mason", "Milliner", "Mirror Maker", "Musket Maker", "Needleworker", "Parchment Maker", "Pencil Maker", "Pipe Maker", "Potter", "Rope Maker", "Rug Maker", "Sculptor", "Shoemaker", "Snowshoe Maker", "Spinner", "Stone Carver", "Sundial Maker", "Tapestry Maker", "Tassel Maker", "Taxidermist", "Tentmaker", "Textile Artist", "Tie Maker", "Umbrella Maker", "Wheelwright", "Wire Weaver", "Yarn Maker", "Zither Maker",
"Janitor", "Housekeeper", "Maid", "Custodian", "Cleaner", "Laundry Attendant", "Dishwasher", "Window Cleaner", "Carpet Cleaner", "Pool Cleaner", "Gutter Cleaner", "Chimney Sweep", "Pressure Washer", "Trash Collector", "Recycling Coordinator", "Biohazard Cleaner", "Crime Scene Cleaner", "Hoarding Specialist", "Sewage System Cleaner", "Air Duct Cleaner", "Ventilation System Cleaner", "Kitchen Exhaust Hood Cleaner", "Graffiti Remover", "Odor Eliminator", "Floor Waxer", "Restroom Cleaner", "Restoration Technician", "Disinfectant Sprayer", "Pest Control Technician", "Rodent Control Technician", "Bird Control Technician", "Animal Waste Cleanup Technician", "Mold Remediation Technician", "Fire and Smoke Damage Restoration Technician", "Water Damage Restoration Technician", "Car Detailer", "Boat Detailer", "Aircraft Detailer", "Pressure Washer Operator", "Swimming Pool Maintenance Technician", "Hot Tub Maintenance Technician", "Sauna Cleaner", "Locker Room Attendant", "Equipment Cleaner", "Stadium Cleaner", "Arena Cleaner", "Amusement Park Cleaner", "Zoo Cleaner", "Aquarium Cleaner", "Museum Cleaner", "Art Gallery Cleaner", "Library Cleaner", "Office Cleaner", "Commercial Cleaner", "Industrial Cleaner", "Warehouse Cleaner", "Oil Spill Cleanup Technician", "Tank Cleaner", "Drain Cleaner", "Hydro Jet Operator", "Chemical Cleaner", "Metal Cleaner", "Jewelry Cleaner", "Watch Cleaner", "Leather Cleaner", "Shoe Cleaner", "Dry Cleaner", "Laundromat Attendant", "Ironing Specialist", "Tailor", "Seamstress", "Garment Repair Specialist", "Fur Cleaner", "Storage Facility Cleaner", "House Sitting Specialist", "Pet Waste Cleanup Specialist", "Mushroom Picker", "Clam Harvester", "Oyster Harvester", "Sea Urchin Harvester", "Seaweed Harvester", "Harvesting Equipment Cleaner", "Tree Trimmer", "Pruner", "Lawn Care Technician", "Gardener", "Hedge Trimmer", "Weed Whacker", "Leaf Blower Operator", "Snow Plow Driver", "Ice and Snow Removal Technician", "Ski Resort Groomer", "Beach Cleaner", "City Street Sweeper", "Parking Lot Sweeper", "Train Cleaner", "Bus Cleaner", "Subway Car Cleaner", "Aircraft Cabin Cleaner", "Cruise Ship Cleaner",
"Captain", "Sailor", "Navigator", "Merchant", "Fisher", "Harpooner", "Deckhand", "Shipwright", "Boatswain", "Carpenter", "Rigger", "Navigator's Assistant", "Cook", "Powder Monkey", "Signalman", "Lookout", "Gunner", "Pirate", "Privateer", "Smuggler", "Fishmonger", "Navigator's Aide", "Marine", "Admiral", "Ferryman", "Ship's Chaplain", "Quartermaster", "Cabin Boy", "Bosun's Mate", "Sailmaker", "Master Gunner", "Ropemaker", "Sexton", "Sailor's Wife", "Sailor's Widow", "Shantyman", "Wreck Master", "Scuba Diver", "Marine Biologist", "Shark Hunter", "Whaler", "Treasure Hunter", "Ship Salvager", "Sea Merchant", "Ship Chandler", "Ship's Surgeon", "Ship's Clerk", "Boat Builder", "Harbor Master", "Lighthouse Keeper", "Ship's Steward", "Maritime Lawyer", "Sea Captain", "Ship Inspector", "Marine Surveyor", "Dock Worker", "Fishing Boat Captain", "Shrimp Boat Captain", "Cargo Loader", "Deck Cleaner", "Galley Slave", "Marine Electrician", "Radar Operator", "Sailboat Instructor", "Dredge Operator", "Tugboat Captain", "Submarine Engineer", "Seafood Processor", "Ship Agent", "Marine Electrician's Mate", "Seaplane Pilot", "Seafloor Surveyor", "Coastal Engineer", "Lighthouse Mechanic", "Marine Archaeologist", "Marine Diesel Mechanic", "Marine Electronics Technician", "Marine Fabricator", "Marine Safety Inspector", "Merchant Mariner", "Motorboat Operator", "Offshore Oil Worker", "Radio Operator", "Ship Broker", "Ship Carpenter", "Ship Chandler's Assistant", "Ship Fitter", "Ship Navigator's Mate", "Ship Painter", "Ship Purser", "Ship Radio Officer", "Ship's Boy", "Ship's Carpenter's Mate", "Ship's Carpenter's Assistant", "Ship's Engineer", "Ship's Fireman", "Ship's Painter's Assistant", "Ship's Plumber", "Ship's Porter", "Ship's Wiper", "Ship's Writer", "Stevedore", "Trawlerman", "Waterman", "Whale Oil Refiner",
"Knight", "Squire", "Archer", "Crossbowman", "Longbowman", "Lancer", "Pikeman", "Halberdier", "Man-at-Arms", "Bannerman", "Scout", "Vanguard", "Rearguard", "Cavalier", "Gunner", "Javelineer", "Slinger", "Spearman", "Swordsman", "Warrior", "Shieldbearer", "Standard-bearer", "Assassin", "Executioner", "Sapper", "Trebuchet operator", "Ballista operator", "Catapult operator", "Siege Engineer", "Battlefield Medic", "Chaplain", "Master-at-Arms", "Bodyguard", "Horseman", "Infantryman", "Militiaman", "Mercenary", "Glaivesman", "Arbalestier", "Bladesmith", "Fletcher", "Armorer", "Weapon-smith", "Siege Master", "Alchemist", "Pyromancer", "Demonologist", "Dark Knight", "Templar", "Crusader", "Inquisitor", "Paladin", "Ranger", "Swashbuckler", "Brigand", "Highwayman", "Berserker", "Viking", "Ninja", "Ronin", "Samurai", "Pirate", "Corsair", "Privateer", "Duelist", "Gladiator", "Tournament Champion", "Hoplite", "Centurion", "Legionnaire", "Champion", "Blademaster", "Blood Knight", "Cavalryman", "Landsknecht", "Hussar", "Musketeer", "Cuirassier", "Dismounter", "Paladin's Squire", "Pike and Shot Man", "Reiter", "Arquebusier", "Lancer of the Guard", "Hauptmann", "Cannon Master", "Commander", "General", "Warlord", "Assault Specialist", "Combat Engineer",
"Dragon Slayer", "Griffin Rider", "Phoenix Tamer", "Unicorn Hunter", "Kraken Wrangler", "Sphinx Riddler", "Manticore Trainer", "Cerberus Keeper", "Chimera Hunter", "Basilisk Tamer", "Hydra Slayer", "Gorgon Trapper", "Harpy Enforcer", "Minotaur Slayer", "Medusa Handler", "Pegasus Trainer", "Centaur Archer", "Cyclops Brawler", "Satyr Musician", "Faun Dancer", "Naga Charmer", "Yeti Tracker", "Ogre Smasher", "Troll Hunter", "Giant Killer", "Gnome Engineer", "Goblin Saboteur", "Kobold Miner", "Merfolk Diver", "Siren Ensnarer", "Kraken Caller", "Shark Hunter", "Octopus Wrangler", "Squid Tamer", "Sea Serpent Slayer", "Phoenix Rider", "Griffin Tamer", "Dragon Keeper", "Unicorn Wrangler", "Hydra Trainer", "Basilisk Handler", "Cerberus Keeper", "Chimera Tamer", "Manticore Hunter", "Gorgon Slayer", "Medusa Hunter", "Pegasus Trainer", "Satyr Brawler", "Cyclops Archer", "Centaur Cavalier", "Yeti Hunter", "Troll Slayer"
]

flaws = [
    "Absent-minded",
    "Abusive",
    "Addicted",
    "Aggressive",
    "Alcoholic",
    "Arrogant",
    "Clumsy",
    "Compulsive liar",
    "Cowardly",
    "Cruel",
    "Cursed",
    "Deceitful",
    "Delusional",
    "Dependent",
    "Desperate",
    "Dishonest",
    "Disloyal",
    "Disorganized",
    "Distrustful",
    "Easily influenced",
    "Envious",
    "Exhibitionist",
    "Fearful",
    "Foolhardy",
    "Forgetful",
    "Greedy",
    "Gullible",
    "Haughty",
    "Hesitant",
    "Hotheaded",
    "Humble",
    "Hunted",
    "Ignorant",
    "Illiterate",
    "Immovable",
    "Impatient",
    "Impulsive",
    "Incompetent",
    "Indecisive",
    "Insecure",
    "Insomniac",
    "Jealous",
    "Lazy",
    "Lethargic",
    "Liar",
    "Lonely",
    "Loudmouthed",
    "Low self-esteem",
    "Martyr complex",
    "Materialistic",
    "Meek",
    "Miserly",
    "Naive",
    "Narcissistic",
    "Neurotic",
    "Night owl",
    "Obsessive",
    "Overconfident",
    "Overemotional",
    "Overprotective",
    "Paranoid",
    "Phobic",
    "Pompous",
    "Possessive",
    "Prejudiced",
    "Proud",
    "Pyromaniac",
    "Reckless",
    "Resentful",
    "Rude",
    "Sadistic",
    "Secretive",
    "Self-centered",
    "Self-destructive",
    "Self-righteous",
    "Short-tempered",
    "Shy",
    "Skeptical",
    "Sleepwalker",
    "Slothful",
    "Slow",
    "Small-minded",
    "Smelly",
    "Spiteful",
    "Stubborn",
    "Stutterer",
    "Superstitious",
    "Suspicious",
    "Taciturn",
    "Tactless",
    "Tardy",
    "Thin-skinned",
    "Timid",
    "Tired",
    "Trapped",
    "Twitchy",
    "Ugly",
    "Unambitious",
    "Uncontrolled",
    "Uncooperative",
    "Undisciplined",
    "Unforgiving",
    "Ungrateful",
    "Unhygienic",
    "Unlucky",
    "Unreliable",
    "Untrustworthy",
    "Vain",
    "Vengeful",
    "Vindictive",
    "Violent",
    "Wanted",
    "Weak-willed",
    "Whiny",
    "Wild",
    "Wishful",
    "Withdrawn",
    "Worrier",
    "OverZealous",
    "Abandoned",
  "Addictive",
  "Agonizing",
  "Alone",
  "Angry",
  "Anxious",
  "Apathetic",
  "Ashamed",
  "Assassin",
  "Avoidant",
  "Betrayer",
  "Bitter",
  "Blind",
  "Bloody",
  "Broken",
  "Brutal",
  "Cannibal",
  "Careless",
  "Chaotic",
  "Chased",
  "Cheater",
  "Cold",
  "Condemned",
  "Confused",
  "Controlling",
  "Coward",
  "Criminal",
  "Crippled",
  "Cruelty",
  "Curse",
  "Cursed",
  "Dangerous",
  "Dark",
  "Dead",
  "Deceiver",
  "Defeated",
  "Defiler",
  "Delusional",
  "Demon",
  "Depressed",
  "Deranged",
  "Deserter",
  "Despair",
  "Destroyed",
  "Detached",
  "Deviant",
  "Devil",
  "Disappointing",
  "Disappeared",
  "Disappointed",
  "Disaster",
  "Discontent",
  "Disgusting",
  "Dishonorable",
  "Disloyalty",
  "Displeased",
  "Disrespected",
  "Distant",
  "Distracted",
  "Disturbed",
  "Divided",
  "Doomed",
  "Double-crosser",
  "Dragon",
  "Dread",
  "Drunk",
  "Dull",
  "Dungeon",
  "Dying",
  "Easily angered",
  "Egoistic",
  "Empty",
  "Enslaved",
  "Envious",
  "Evil",
  "Exhausted",
  "Explosive",
  "False",
  "Famine",
  "Fanatic",
  "Fearful",
  "Feral",
  "Fickle",
  "Fighting",
  "Filthy",
  "Foolish",
  "Forgotten",
  "Forsaken",
  "Foul",
  "Frantic",
  "Frustrated",
  "Fugitive",
  "Furious",
  "Ghoul",
  "Glutton",
  "Gloomy",
  "Goblin",
  "Grief",
  "Grim",
  "Grudge",
  "Guilt",
  "Hateful",
  "Haunted",
  "Havoc",
  "Helpless",
  "Hesitant",
  "Hopeless",
  "Horror",
  "Humiliated",
  "Hunted",
  "Hysterical",
  "Ignorance",
  "Immobile",
  "Immoral",
  "Impotent",
  "Inadequate",
  "Infected",
  "Inferior",
  "Injured",
  "Insecure",
  "Insidious",
  "Insolvent",
  "Intimidated",
  "Invalid",
  "Invaded",
  "Socially Invisible",
  "Autistic",
  "Socially Inept",
  "Abomination",
  "Abysmal",
  "Addled",
  "Adulterer",
  "Aggressive",
  "Alienated",
  "Amoral",
  "Amputee",
  "Anarchist",
  "Anemic",
  "Anguished",
  "Anorexic",
  "Antagonistic",
  "Apathy",
  "Apostate",
  "Arrogant",
  "Ashen",
  "Asphyxiated",
  "Assassin's Mark",
  "Astral",
  "Atrophied",
  "Avaricious",
  "Backstabber",
  "Banned",
  "Barbarian",
  "Barren",
  "Beastly",
  "Bedridden",
  "Befouled",
  "Beggar",
  "Berserker",
  "Betrayed",
  "Bewitched",
  "Bigoted",
  "Bitten",
  "Blackhearted",
  "Bleeding",
  "Blindness",
  "Bloodsucker",
  "Boastful",
  "Body Dysmorphic Disorder",
  "Bored",
  "Brainless",
  "Brawler",
  "Broken-hearted",
  "Brutish",
  "Bullied",
  "Butcher",
  "Cadaverous",
  "Cancerous",
  "Captive",
  "Cataleptic",
  "Catatonic",
  "Cauldron-born",
  "Censor",
  "Changeling",
  "Chaos-born",
  "Chariot",
  "Charming",
  "Chastity Belt",
  "Chatterbox",
  "Choleric",
  "Chosen",
  "Chrono-displaced",
  "Clandestine",
  "Clumsy",
  "Cocky",
  "Codependent",
  "Coffin-bound",
  "Cold-hearted",
  "Commanding",
  "Compromised",
  "Conceited",
  "Condemned to Hell",
  "Confused Identity",
  "Conspirator",
  "Contagious",
  "Contraband",
  "Cowardly",
  "Crippled Soul",
  "Crooked",
  "Cruel-hearted",
  "Crypt-bound",
  "Cursed by God",
  "Damned",
  "Darkness",
  "Deadbeat",
  "Deafened",
  "Deceitful",
  "Decrepit",
  "Demonic",
  "Dependent",
  "Depressive",
  "Desecrator",
  "Desolate",
  "Despairing",
  "Destitute",
  "Destroyed Psyche",
  "Detonator",
  "Devastated",
  "Devil's Child",
  "Diabolic",
  "Difficult",
  "Diminished",
  "Disappointer",
  "Disastrous",
  "Discontented",
  "Discouraged",
  "Disenchanted",
  "Disfigured",
  "Disgraced",
  "Disgusting Appearance",
  "Disheartened",
  "Dishonest",
  "Disillusioned",
  "Disintegrating",
  "Disliked",
  "Disloyal",
  "Dismembered",
  "Disowned",
  "Displaced",
  "Disrespectful",
  "Distrusting",
  "Disturbed Mind",
  "Doomed Soul",
  "Double-crossed",
  "Goblin's Sneer",
"Griffin's Pride",
  "Abhorred by Beasts",
  "Alien to Nature",
  "Amphibious",
  "Animal Magnetism",
  "Arachnophobic",
  "Avian Foe",
  "Beastmaster's Bane",
  "Bestial",
  "Black Sheep",
  "Bloodhound",
  "Boarish",
  "Bovine Stare",
  "Butterfly Effect",
  "Canine Instincts",
  "Catatonic in Bright Light",
  "Compulsive Liar",
  "Coveted Hide",
  "Cowardly Lion",
  "Crazy Like a Fox",
  "Cursed by the Moon",
  "Darkness Incarnate",
  "Deep Sea Phobia",
  "Demon Possessed",
  "Demonic Familiar",
  "Despicable Rodent",
  "Devil's Advocate",
  "Dire Wolf's Curse",
  "Disfigured Beak",
  "Displaced from Nature",
  "Dogged Pursuit",
  "Dolphin's Lament",
  "Dragon's Bane",
  "Draugr's Burden",
  "Dread of the Deep",
  "Dungeon Rat",
  "Acne-Prone",
  "Alopecia",
  "Asymmetrical Face",
  "Balding",
  "Beard Patchiness",
  "Big Ears",
  "Birthmark",
  "Blotchy Skin",
  "Blue Veins",
  "Bow-Legged",
  "Broken Nose",
  "Buck Teeth",
  "Burn Scars",
  "Bushy Eyebrows",
  "Cellulite",
  "Clubbed Fingers",
  "Crooked Teeth",
  "Cross-Eyed",
  "Crow's Feet",
  "Deep Set Eyes",
  "Double Chin",
  "Droopy Eyelids",
  "Eczema",
  "Enlarged Pores",
  "Excessive Sweating",
  "Flabby Arms",
  "Flared Nostrils",
  "Flat Chest",
  "Freckles",
  "Gapped Teeth",
  "Ginger Hair",
  "Gray Hair",
  "Hairy Arms",
  "Heavy Lidded",
  "High Forehead",
  "Hollow Cheeks",
  "Huge Nose",
  "Hunchbacked",
  "Hyperpigmentation",
  "Inverted Nipples",
  "Jaundiced",
  "Knobby Knees",
  "Large Forehead",
  "Liver Spots",
  "Long Neck",
  "Lost a Tooth",
  "Love Handles",
  "Low-Hanging Belly",
  "Moles",
  "Narrow Shoulders",
  "Nasal Flaring",
  "Overbite",
  "Patchy Beard",
  "Pierced Nose",
  "Pigmented Skin",
  "Pimples",
  "Pointy Ears",
  "Potbelly",
  "Psoriasis",
  "Receding Hairline",
  "Rosacea",
  "Round Face",
  "Scars",
  "Scruffy Beard",
  "Shaggy Hair",
  "Short Legs",
  "Shrill Voice",
  "Skeletal Build",
  "Skin Tags",
  "Small Mouth",
  "Squinty Eyes",
  "Stained Teeth",
  "Strabismus",
  "Stretch Marks",
  "Sunken Cheeks",
  "Sweaty Palms",
  "Thick Neck",
  "Thin Lips",
  "Thinning Hair",
  "Uneven Eyebrows",
  "Unibrow",
  "Upturned Nose",
  "Varicose Veins",
  "Warts",
  "Webbed Toes",
  "Widow's Peak",
  "Yellow Teeth",
  "Addictive Personality",
  "Alcoholism",
  "Anger Management Issues",
  "Avarice",
  "Bitterness",
  "Compulsive Gambling",
  "Con Artist",
  "Cruelty",
  "Deceitful",
  "Defensive",
  "Delusional",
  "Dependent",
  "Desperate",
  "Disloyal",
  "Distrustful",
  "Drug Addiction",
  "Envy",
  "Excessive Pride",
  "Explosive Temper",
  "Fanaticism",
  "Gluttony",
  "Greed",
  "Hedonism",
  "Hypocrisy",
  "Impulsive",
  "Indolence",
  "Infidelity",
  "Insecure",
  "Insomniac",
  "Jealousy",
  "Laziness",
  "Lustful",
  "Megalomania",
  "Mendacious",
  "Misogynistic",
  "Narcissism",
  "Narrow-Minded",
  "Nihilistic",
  "Obsessive",
  "Paranoia",
  "Pessimistic",
  "Phobia",
  "Power Hungry",
  "Prejudice",
  "Prideful",
  "Procrastination",
  "Pyromania",
  "Rage",
  "Ruthlessness",
  "Sadism",
  "Selfishness",
  "Self-Loathing",
  "Self-Pity",
  "Skepticism",
  "Slothful",
  "Stingy",
  "Stubbornness",
  "Superiority Complex",
  "Suspicious",
  "Tactless",
  "Thievery",
  "Tyranny",
  "Ungrateful",
  "Vanity",
  "Vengeful",
  "Violent",
  "Vulgar",
  "Workaholic",
  "Xenophobia",
  "Yielding",
  "Zealotry",
  "Amputated Limb",
  "Blind",
  "Clumsy",
  "Deaf",
  "Dwarfism",
  "Frail",
  "Gimpy",
  "Hunchbacked",
  "Lame",
  "Missing Eye",
  "Missing Limb",
  "One Arm",
  "One Ear",
  "One Eye",
  "One Leg",
  "Paralyzed",
  "Short",
  "Slow",
  "Small Hands",
  "Small Stature",
  "Thin",
  "Tiny",
  "Underdeveloped",
  "Underweight",
  "Unsteady",
  "Weak Bones",
  "Weak Grip",
  "Weak Heart",
  "Weak Immune System",
  "Weak Legs",
  "Weak Lungs",
  "Weak Muscles",
  "Weak Spine",
  "Wheelchair Bound",
  "Albino",
  "Burned",
  "Clubfooted",
  "Cross-Eyed",
  "Double Jointed",
  "Freckled",
  "Hairy",
  "Lanky",
  "Large Ears",
  "Large Nose",
  "Large Stature",
  "Obese",
  "Overweight",
  "Pointy Ears",
  "Potbellied",
  "Rash",
  "Rickets",
  "Runt",
    "Absent-minded",
    "Always hungry",
    "Always running late",
    "Can't stand spicy food",
    "Chronic procrastinator",
    "Clumsy",
    "Compulsive fidgeter",
    "Constantly misplaces items",
    "Cracks knuckles constantly",
    "Easily distracted",
    "Fidgety",
    "Forgets important dates",
    "Frequently gets lost",
    "Gets carsick easily",
    "Gets motion sickness easily",
    "Has a tendency to overthink",
    "Has a tendency to talk too much",
    "Has trouble saying no",
    "Hates the taste of coffee",
    "Inconsistent sleep schedule",
    "Interrupts others often",
    "Leaves lights on unnecessarily",
    "Loses track of time easily",
    "Loud chewer",
    "Messy eater",
    "Mumbles when speaking",
    "Neat freak",
    "Needs to double-check everything",
    "Nervous fidgeter",
    "Overthinks decisions",
    "Overuses filler words",
    "Picks at nails",
    "Picky eater",
    "Procrastinates often",
    "Puts things off until the last minute",
    "Runs out of battery frequently",
    "Sensitive to strong smells",
    "Skips meals often",
    "Slight hearing impairment",
    "Snacks too much",
    "Snores loudly",
    "Sometimes forgets to reply to messages",
    "Spends too much time on social media",
    "Stutters",
    "Talks too loudly",
    "Terrible sense of direction",
    "Terrible sense of humor",
    "Terrible memory",
    "Terrible with names",
    "Tendency to interrupt",
    "Thinks out loud",
    "Trouble following instructions",
    "Trouble making decisions",
    "Trouble paying attention",
    "Uncomfortable in silence",
    "Unorganized",
    "Very forgetful",
    "Wanders off easily",
    "Weak sense of smell",
    "Weak sense of taste",
    "Wears mismatched socks often",
    "Wears the wrong shoes",
    "Works slowly",
    "Writes illegibly",
    "Worries too much",
    "Often spills food or drinks",
    "Slightly colorblind",
    "Has trouble expressing themselves",
    "Has trouble understanding sarcasm",
    "Has trouble with small talk",
    "Hesitant decision-maker",
    "Indecisive",
    "Irritated by certain textures",
    "Jittery",
    "Lacks patience",
    "Leaves doors open",
    "Leaves phone on silent often",
    "Loses things easily",
    "Makes simple math mistakes",
    "Messy handwriting",
    "Mumbles or speaks too quietly",
    "Needs to have things a certain way",
    "Overthinks social interactions",
    "Overuses emojis or abbreviations",
    "Perfectionist",
    "Picks at skin",
    "Picks their nose",
    "Poor listener",
    "Prone to daydreaming",
    "Procrastinates on phone calls",
    "Puts things off until they become urgent",
    "Rambles when speaking",
    "Says 'um' or 'uh' often",
    "Slight tremble in hands",
    "Slightly forgetful",
    "Snacks on unhealthy foods too often",
    "Snaps at people easily",
    "Sometimes forgets to eat",
    "Sometimes talks too much",
    "Always Forgetting Something",
    "Bad Sense of Direction",
    "Bitten by Mosquitoes Often",
    "Can't Stand Spicy Food",
    "Car Sickness",
    "Chronic Sneezing",
    "Clumsy",
    "Constantly Forgetting Names",
    "Cracking Knuckles Habitually",
    "Difficulty Tying Knots",
    "Dislikes Being Hugged",
    "Drinks Too Much Water",
    "Easily Distracted",
    "Eats Too Fast",
    "Forgets to Check Mail",
    "Frequent Need to Pee",
    "Gets Motion Sick on Boats",
    "Gets Sunburned Easily",
    "Gets Tired Easily",
    "Hiccups Often",
    "Hoards Junk",
    "Hums Constantly",
    "Impatient",
    "Inability to Whistle",
    "Insomnia",
    "Itchy Nose",
    "Jumpy",
    "Leaves the Stove On",
    "Loses Keys Often",
    "Loud Snoring",
    "Lousy Penmanship",
    "Loves to Procrastinate",
    "Makes Bad Puns",
    "Mispells Words Often",
    "Nail Biting",
    "Needs Glasses to Read",
    "No Sense of Rhythm",
    "Noisy Eater",
    "Often Forgets Umbrella",
    "Overreacts to Everything",
    "Overuses Abbreviations",
    "Picks at Nails",
    "Poor Handwriting",
    "Prefers to Wear Mismatched Socks",
    "Procrastinates Often",
    "Puts Salt on Everything",
    "Repeats Stories Often",
    "Restless Leg Syndrome",
    "Scattered Thoughts",
    "Says 'um' and 'ah' a Lot",
    "Says 'like' Too Much",
    "Sings Off-Key",
    "Sneezes Loudly",
    "Snores Loudly",
    "Sore Loser",
    "Spills Drinks Often",
    "Stays Up Too Late",
    "Stops in the Middle of Sentences",
    "Talks Too Much",
    "Taps Feet Constantly",
    "Tendency to Interrupt Others",
    "Terrible at Small Talk",
    "Terrible Memory",
    "Terrible Singing Voice",
    "Thinks Out Loud",
    "Throws Out Important Papers",
    "Tongue-Tied",
    "Trouble Sitting Still",
    "Unorganized",
    "Unreliable Memory",
    "Unsteady Hand",
    "Uses Too Much Cologne/Perfume",
    "Vague",
    "Very Bad Breath",
    "Very Loud Sneezing",
    "Wakes Up Late",
    "Walks Loudly",
    "Weak Bladder",
    "Wears Mismatched Shoes",
    "Wears Too Much Jewelry",
    "Wears Too Much Makeup",
    "Whistles Constantly",
    "Won't Stop Talking About Their Pet",
    "Writes Too Small",
    "Writes Too Big",
    "Zones Out Frequently"
]

version = "10/12/23"


#3PP Content:
#Combat Spheres:
combat_spheres = ["Alchemy","Athletics","Barrage","Barroom","Beastmastery","Berserker","Boxing","Brute","Dual Wielding","Duelist","Equipment","Fencing","Gladiator","Guardian","Lancer","Open Hand","Scoundrel","Scout","Shield","Sniper","Trap","Warleader","Wrestling"]
#magic spheres:
magic_spheres = ["Alteration","Blood","Conjuration","Creation","Dark","Death","Destruction","Divination","Enhancement","Fallen Fey","Fate","Illusion","Life","Light","Mana","Mind","Nature","Protection","Telekinesis","Time","War","Warp","Weather"]
#skill spheres:
skill_spheres = ["Artifice", "Bluster", "Body Control", "Communication", "Faction", "Herbalism", "Infiltration", "Investigation", "Navigation", "Performance", "Spellhacking", "Study", "Subterfuge", "Survivalism", "Vocation"]



#path of war classes:
path_of_war_class = ['Warder', 'Harbinger', 'Mystic', 'Zealot', 'Stalker']
disciplines = ["Black Seraph", "Broken Blade", "Brutal Crocodile", "Cursed Razor", "Elemental Flux", "Eternal Guardian", "Fools Errand", "Golden Lion", "Iron Tortoise", "Leaden Hyena", "Mangled Gear", "Mithral Current", "Piercing Thunder", "Primal Fury", "Radiant Dawn", "Riven Hourglass", "Roaring Mouse", "Sagitta Stellaris", "Scarlet Throne", "Shattered Mirror", "Silver Crane", "Sleeping Goddess", "Solar Wind", "Spark of Battle", "Steel Serpent", "Surging Shark", "Tempest Gale", "Thrashing Dragon", "Unquiet Grave", "Veiled Moon"]
