races = {
    'Human': {
        'first names': {
            'Calishite': ['Aseir', 'Bardeid', 'Haseid', 'Khemed', 'Mehmen', 'Sudeiman', 'Zasheir'],
            'Chondathan': ['Darvin', 'Dorn', 'Evendur', 'Gorstag', 'Grim', 'Helm', 'Malark', 'Morn', 'Randal', 'Stedd'],
            'Damaran': ['Bor', 'Fodel', 'Glar', 'Grigor', 'Igan', 'Ivor', 'Kosef', 'Mival', 'Orel', 'Pavel', 'Sergor'],
            'Illuskan': ['Ander', 'Blath', 'Bran', 'Frath', 'Geth', 'Lander', 'Luth', 'Malcer', 'Stor', 'Taman', 'Urth'],
            'Mulan': ['Aoth', 'Bareris', 'Ehput Ki', 'Kethoth', 'Mumed', 'Ramas', 'So Kehur', 'Thazar De', 'Urhur'],
            'Rashemi': ['Borivik', 'Faurgar', 'Jandar', 'Kanithar', 'Madislak', 'Ralmevik', 'Shaumar', 'Vladislak'],
            'Shou': ['Chien', 'Huang', 'Kao', 'Kung', 'Lao', 'Ling', 'Mei', 'Pin', 'Shin', 'Sum', 'Tan', 'Wan'],
            'Turami': ['Anton', 'Diero', 'Marcon', 'Pieron', 'Rimardo', 'Romero', 'Salazar', 'Umbero']
        },
        'last names': {
            'Calishite': ['Basha', 'Dumein', 'Jassan', 'Khalid', 'Mostana', 'Pashar', 'Rein'],
            'Chondathan': ['Amblecrown', 'Buckman', 'Dundragon', 'Evenwood', 'Greycastle', 'Tallstag'],
            'Damaran': ['Bersk', 'Chernin', 'Dotsk', 'Kulenov', 'Marsk', 'Nemetsk', 'Shemov', 'Starag'],
            'Illuskan': ['Brightwood', 'Helder', 'Hornraven', 'Lackman', 'Stormwind', 'Windrivver'],
            'Mulan': ['Ankhalab', 'Anskuld', 'Fezim', 'Hahpet', 'Nathandem', 'Sepret', 'Uuthrakt'],
            'Rashemi': ['Ankhalab', 'Anskuld', 'Fezim', 'Hahpet', 'Nathandem', 'Sepret', 'Uuthrakt'],
            'Shou': ['An', 'Chen', 'Chi', 'Fai', 'Jiang', 'Jun', 'Lian', 'Long', 'Meng', 'On', 'Shan', 'Shui', 'Wen'],
            'Turami': ['Agosto', 'Astorio', 'Calabra', 'Domine', 'Falone', 'Marivaldi', 'Pisacar', 'Ramondo']
        },
        'group': ['Calishite', 'Chondathan', 'Damaran', 'Illuskan', 'Mulan', 'Rashemi', 'Shou', 'Turami'],
        'age': (15, '1d6'),
        'height': (58, '2d4'),
        'weight': (120, '2d6'),
        'size': 'Medium',
        'speed': 30,
        'traits': ['Versatility'],
        'languages': ['Elven', 'Draconic', 'Gnoll', 'Gnome', 'Goblin', 'Orc', 'Sylvan'],
    },

		'Dragonborn': {
			'first names': ['Agon', 'Egon', 'Sugissa', 'Qixiris', 'Nysriel', 'Qicoria', 'Phidalynn', 'Wraxiris', 'Orinn', 'Yrsaadi', 'Mathtuan', 'Nysqorel', 'Zenpora', 'Wradalynn',],
			'last names': ['Shunxash', 'Girrhiliar', 'Nyelkanshteth', 'Dommicmellir', 'Preapinshtondeth', 'Karjualath', 'Cardaseargual', 'Fambucoth', '', '', 'Priarindraandin', 'Aapos'],
			'age': (79,'6d6'),
			'height': (182, '2d6'),
			'weight': (210, '1d6'),
			'size': 'Medium',
			'speed': 30,
			'traits': ['Draconic Ancestory', 'Increased Resistance'],
			'languages': ['Draconic', 'Undercommon']
		},

    'Elf': {
        'first names': ['Adran', 'Aelar', 'Aramil', 'Arannis', 'Aust', 'Beiro', 'Berrian', 'Carric', 'Enialis', 'Erdan', 'Erevan', 'Galinndan', 'Hadarai', 'Heian', 'Himo', 'Immeral', 'Ivellios', 'Laucian', 'Mindartis', 'Paelias',
                        'Peren', 'Quarion', 'Riardon', 'Rolen', 'Soveliss', 'Thamior', 'Tharivol', 'Theren', 'Varis'],
        'last names': ['Amakiir', 'Amastacia', 'Galanodel', 'Holimion', 'Ilphelkiir', 'Liadon', 'Meliamne', 'Naïlo', 'Siannodel', 'Xiloscient'],
        'age': (110, '6d6'),
        'height': (58, '2d6'),
        'weight': (85, '1d6'),
        'size': 'Medium',
        'speed': 30,
        'traits': ['Darkvision', 'Fey Ancestory'],
        'languages': ['Elven', 'Draconic', 'Gnoll', 'Gnome', 'Goblin', 'Orc', 'Sylvan'],
    },

    'Gnome': {
        'first names': ['Boddynock', 'Dimble', 'Fonkin', 'Gimble', 'Glim', 'Gerbo', 'Jebeddo', 'Namfoodle', 'Roondar', 'Seebo', 'Zook'],
        'last names': ['Beren', 'Daergel', 'Folkor', 'Garrick', 'Nackle', 'Murnig', 'Ningel', 'Raulnor', 'Scheppen', 'Turen'],
        'nick names': ['Aleslosh', 'Ashhearth', 'Badger', 'Cloak', 'Doublelock', 'Filchbatter', 'Fnipper', 'Oneshoe', 'Sparklegem', 'Stumbleduck'],
        'age': (40, '6d6'),
        'height': (36, '2d4'),
        'weight': (40, '1d6'),
        'size': 'Small',
        'speed': 20,
        'traits': ['Tinker'],
        'languages': ['Gnomish', 'Draconic', 'Dwarvish', 'Elven', 'Giant', 'Goblin', 'Orc']
    },

    'Halfling': {
        'first names': ['Alton', 'Ander', 'Cade', 'Corrin', 'Eldon', 'Errich', 'Finnan', 'Garret', 'Lindal', 'Lyle', 'Merric', 'Milo', 'Osborn', 'Perrin', 'Reed', 'Roscoe', 'Wellby'],
        'last names': ['Brushgather', 'Goodbarrel', 'Greenbottle', 'Highhill', 'Hilltopple', 'Leagallow', 'Tealeaf', 'Thorngage', 'Tosscobble', 'Underbough'],
        'age': (20, '3d6'),
        'height': (32, '2d4'),
        'weight': (30, '1d1'),
        'size': 'Small',
        'speed': 20,
        'traits': ['Brave', 'Halfling Nimbleness'],
        'languages': ['Halfling', 'Dwarvish', 'Elven', 'Gnomish', 'Goblin', 'Orc']
    },

    'Dwarf': {
        'first names': ['Adrik', 'Alberich', 'Baern', 'Barendd', 'Brottor', 'Bruenor', 'Dain', 'Darrak', 'Delg', 'Eberk', 'Einkil', 'Fargrim', 'Flint', 'Gardain', 'Harbek', 'Kildrak', 'Morgran', 'Orsik', 'Oskar', 'Rangrim', 'Rurik','Taklinn', 'Thoradin', 'Thorin', 'Tordek', 'Traubon', 'Travok', 'Ulfgar', 'Veit', 'Vondal'],
        'last names': ['Balderk', 'Battlehammer', 'Brawnanvil', 'Dankil', 'Fireforge', 'Frostbeard', 'Gorunn', 'Holderhek', 'Ironfist', 'Loderr', 'Lutgehr', 'Rumnaheim', 'Strakeln', 'Torunn', 'Ungart'],
        'clans': ['Balderk', 'Dankil', 'Gorunn', ' Holderhek', 'Loderr', 'Lutgehr', 'Rumnaheim', 'Strakeln', 'Torunn', 'Ungart'],
        'age': (40, '5d6'),
        'height': (45, '2d4'),
        'weight': (130, '2d6'),
        'size': 'Medium',
        'speed': 20,
        'traits': ['Darkvision', 'Dwarven Resilience'],
        'languages': ['Dwarvish', 'Giant', 'Gnomish', 'Goblin', 'Orc', 'Undercommon'],
    },
    
    'Half-Elf': {
        'age': (20, '2d6'),
        'height': (55, '2d8'),
        'weight': (100, '2d4'),
        'size': 'Medium',
        'speed': 30,
        'traits': ['Darkvision', 'Fey Ancestory'],
        'languages': ['Dwarvish', 'Giant', 'Gnomish', 'Goblin', 'Orc', 'Undercommon'],
    },

    'Half-Orc': {
        'first names': ['Dench', 'Feng', 'Gell', 'Henk', 'Holg', 'Imsh', 'Keth', 'Krusk', 'Ront', 'Shump', 'Thokk'],
        'age': (14, '1d6'),
        'height': (58, '2d12'),
        'weight': (150, '2d6'),
        'size': 'Medium',
        'speed': 30,
        'traits': ['Darkvision', 'Savage Attacks'],
        'languages': ['Orc', 'Draconic', 'Giant', 'Gnoll', 'Goblin', 'Abyssal']
    },
}

classes = {
    'Barbarian': {
        'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
        'armor': ['Padded', 'Leather', 'Studded Leather', 'Hide', 'Chain Shirt', 'Scale Mail', 'Breastplate', 'Half Plate'],
        'skills': ['Acrobatics', 'Animal Handling', 'Athletics', 'Intimidate', 'Nature', 'Perception', 'Survival'],
        'abilities': ['Rage', 'Unarmored Defense', 'Reckless Abandon'],
        'hp': 12,
        'gold': '3d6',
        'saving throws': ['Fortitude', 'Reflex']
},

    'Bard': {
    'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],    
    'armor': ['Padded', 'Leather', 'Studded Leather'],
    'skills': ['Acrobatics', 'Appraise', 'Bluff', 'Climb', 'Diplomacy', 'Disguise', 'Escape Artist', 'Intimidate', 'Knowledge (all skills taken individually)', 'Linguistics', 'Perception', 'Perform (all skills taken individually)', 'Sense Motive', 'Sleight of Hand', 'Spellcraft', 'Stealth', 'Use Magic Device'],
    'abilities': ['Bardic Knowledge', 'Bardic Performance'],
    'hp': 8,
    'gold': '3d6',
    'saving throws': ['Fortitude', 'Will']
},

'Cleric': {
    'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
    'armor': ['Padded', 'Leather', 'Studded Leather', 'Chain Shirt', 'Scale Mail', 'Breastplate', 'Splint Mail', 'Banded Mail', 'Half Plate', 'Full Plate'],
    'skills': ['Appraise', 'Craft (all skills taken individually)', 'Diplomacy', 'Heal', 'Knowledge (arcana)', 'Knowledge (history)', 'Knowledge (nobility)', 'Knowledge (planes)', 'Knowledge (religion)', 'Linguistics', 'Profession (all skills taken individually)', 'Sense Motive', 'Spellcraft'],
    'abilities': ['Channel Energy', 'Spontaneous Casting'],
    'hp': 8,
    'gold': '5d6',
    'saving throws': ['Fortitude', 'Will']
},

    'Druid': {
        'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
        'armor': ['Padded', 'Leather', 'Studded Leather'],
        'skills': ['Craft (Alchemy)', 'Handle Animal', 'Heal', 'Knowledge (Geography)', 'Knowledge (Nature)', 'Perception', 'Spellcraft', 'Survival'],
        'abilities': ['Spontaneous Casting (Summon Nature’s Ally)', 'Nature Sense', 'Wild Empathy', 'Woodland Stride', 'Trackless Step', 'Resist Nature’s Lure', 'Wild Shape'],
        'hp': 8,
        'gold': '2d4',
        'saving throws': ['Fortitude', 'Reflex', 'Will']
},

 'Fighter': {
    'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
    'armor': ['Padded', 'Leather', 'Studded Leather', 'Hide', 'Chain Shirt', 'Scale Mail', 'Breastplate', 'Banded Mail', 'Half-Plate', 'Full Plate'],
    'skills': ['Climb', 'Handle Animal', 'Intimidate', 'Knowledge (dungeoneering)', 'Knowledge (engineering)', 'Profession', 'Ride', 'Survival', 'Swim'],
    'abilities': ['Bravery', 'Weapon Training'],
    'hp': 10,
    'gold': '5d4',
    'saving throws': ['Fortitude', 'Reflex']
},

'Monk': {
    'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
    'armor': ['None'],
    'skills': ['Acrobatics', 'Climb', 'Craft', 'Escape Artist', 'Intimidate', 'Knowledge (history)', 'Knowledge (religion)', 'Perception', 'Perform', 'Profession', 'Ride', 'Sense Motive', 'Stealth', 'Swim'],
    'abilities': ['Flurry of Blows', 'Unarmed Strike', 'Evasion', 'Still Mind'],
    'hp': 8,
    'gold': '2d10',
    'saving throws': ['Fortitude', 'Will']
},

  'Paladin': {
    'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
    'armor': ['Padded', 'Leather', 'Studded Leather', 'Hide', 'Chain Shirt', 'Scale Mail', 'Breastplate', 'Banded Mail', 'Half-Plate', 'Full Plate'],
    'skills': ['Diplomacy', 'Handle Animal', 'Heal', 'Knowledge (nobility)', 'Knowledge (religion)', 'Profession', 'Ride', 'Sense Motive'],
    'abilities': ['Aura of Good', 'Detect Evil', 'Smite Evil', 'Lay on Hands'],
    'hp': 10,
    'gold': '5d4',
    'saving throws': ['Fortitude', 'Will']
},

'Ranger': {
'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
'armor': ['Padded', 'Leather', 'Studded Leather', 'Hide', 'Chain Shirt', 'Scale Mail', 'Breastplate', 'Half-Plate'],
'skills': ['Climb', 'Handle Animal', 'Heal', 'Intimidate', 'Knowledge (dungeoneering)', 'Knowledge (geography)', 'Knowledge (nature)', 'Perception', 'Ride', 'Stealth', 'Survival', 'Swim'],
'abilities': ['Favored Enemy', 'Track', 'Wild Empathy'],
'hp': 8,
'gold': '5d6',
'saving throws': ['Fortitude', 'Reflex']
},

'Rogue': {
    'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
    'armor': ['Padded', 'Leather', 'Studded Leather'],
    'skills': ['Acrobatics', 'Appraise', 'Bluff', 'Climb', 'Craft', 'Diplomacy', 'Disable Device', 'Disguise', 'Escape Artist', 'Intimidate', 'Knowledge (dungeoneering)', 'Knowledge (local)', 'Linguistics', 'Perception', 'Perform', 'Sense Motive', 'Sleight of Hand', 'Stealth', 'Swim', 'Use Magic Device'],
    'abilities': ['Sneak Attack', 'Trapfinding', 'Evasion', 'Rogue Talents'],
    'hp': 6,
    'gold': '4d6',
    'saving throws': ['Reflex', 'Will']
},

'Sorcerer': {
    'weapons': ['Club', 'Dagger', 'Heavy Crossbow', 'Light Crossbow', 'Quarterstaff'],
    'armor': ['None'],
    'skills': ['Appraise', 'Bluff', 'Fly', 'Intimidate', 'Knowledge (arcana)', 'Spellcraft', 'Use Magic Device'],
    'abilities': ['Bloodline', 'Cantrips', 'Eschew Materials'],
    'spells': ['Acid Splash', 'Detect Magic', 'Light', 'Mage Hand', 'Mending', 'Message', 'Prestidigitation', 'Ray of Frost', 'Read Magic'],
    'hp': 4,
    'gold': '3d6',
    'saving throws': ['Fortitude', 'Will']
},

'Warlock': {    
'weapons': ['Club', 'Dagger', 'Heavy Crossbow', 'Light Crossbow', 'Quarterstaff'],
'armor': ['Padded', 'Leather', 'Studded Leather'],
'skills': ['Bluff', 'Craft (any one)', 'Escape Artist', 'Intimidate', 'Knowledge (arcana)', 'Knowledge (planes)', 'Perception', 'Sense Motive', 'Spellcraft', 'Use Magic Device'],
'abilities': ['Otherwordly Patron', 'Eldritch Blast'],
'invocations': ['Beguiling Influence', 'Darkness', 'Devils Sight', 'See the Unseen', 'Walk Unseen'],
'hp': 8,
'gold': '3d6',
'saving throws': ['Fortitude', 'Reflex']
},

'Wizard': {
    'weapons': ['Club', 'Dagger', 'Heavy Crossbow', 'Light Crossbow', 'Quarterstaff'],
    'armor': ['None'],
    'skills': ['Craft (any one)', 'Fly', 'Knowledge (arcana)', 'Knowledge (history)', 'Knowledge (planes)', 'Linguistics', 'Spellcraft'],
    'abilities': ['Arcane Bond', 'Arcane School'],
    'hp': 6,
    'gold': '3d6',
    'saving throws': ['Fortitude', 'Reflex']
},

    'Stalker': {
        'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
        'armor': ['Light Armor', 'Shields'],
        'skills': ['Acrobatics','Climb','Craft','Disable Device','Disguise','Escape Artist','Handle Animal','Heal','Intimidate','Knowledge (dungeoneering)','Knowledge (geography)','Knowledge (nature)','Perception','Ride','Sense Motive','Stealth','Survival','Swim'],
        'hp': 10,
        'gold': '3d6x10',
        'saving throws': ['Fortitude', 'Reflex']
    },

    'Warder': {
        'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
        'armor': ['Heavy Armor', 'Medium Armor', 'Shields'],
        'skills': ["Acrobatics", "Autohypnosis", "Climb", "Craft", "Handle Animal", "Intimidate", "Jump", "Knowledge (engineering)", "Knowledge (history)", "Knowledge (nobility)", "Knowledge (tactics)", "Perception", "Perform", "Profession", "Ride", "Sense Motive", "Survival", "Swim", "Use Rope"],
        'hp': 12,
        'gold': '3d6x10',
        'saving throws': ['Fortitude', 'Will']
    },

    'Warlord': {
        'weapons': ['Axe, Throwing', 'Axe, Two-Bladed', 'Axe, Battle', 'Chain, Spiked','Club', 'Crossbow, Hand', 'Crossbow, Heavy', 'Crossbow, Light','Dagger', 'Dagger, Punching', 'Falchion', 'Flail', 'Flail, Dire','Gauntlet', 'Gauntlet, Spiked', 'Glaive', 'Glaive, Guisarme', 'Greataxe','Greatclub', 'Greatsword', 'Guisarme', 'Halberd', 'Hammer, Gnome Hooked','Hammer, Light', 'Hammer, Lucerne', 'Handaxe', 'Javelin', 'Lance','Longbow', 'Longspear', 'Longsword', 'Mace, Heavy', 'Mace, Light','Morningstar', 'Pick, Heavy', 'Pick, Light', 'Ranseur', 'Rapier','Sap', 'Scimitar', 'Scythe', 'Shortbow', 'Shortspear', 'Shuriken','Siangham', 'Sickle', 'Spear', 'Spear, Hekatonkheires', 'Spiked Armor','Spiked Shield', 'Spiked Gauntlet', 'Staff', 'Sword, Bastard','Sword Cane', 'Sword, Short', 'Trident', 'Urgrosh, Double','Warhammer', 'Whip'],
        'armor': ['Heavy Armor', 'Medium Armor', 'Light Armor', 'Shields'],
        'skills': ['Acrobatics', 'Appraise', 'Bluff', 'Climb', 'Craft', 'Diplomacy', 'Disable Device', 'Disguise', 'Escape Artist', 'Fly', 'Handle Animal', 'Heal', 'Intimidate', 'Knowledge (all)', 'Linguistics', 'Perception', 'Perform', 'Profession', 'Ride', 'Sense Motive', 'Sleight of Hand', 'Spellcraft', 'Stealth', 'Survival', 'Swim', 'Use Magic Device'],
        'hp': 10,
        'gold': '4d6x10',
        'saving throws': ['Fortitude', 'Will']

    }
}

weapon_groups = ['Axes', 'Blades, Heavy', 'Blades, Light', 'Bows', 'Close', 'Crossbows', 'Double', 'Firearms', 'Flails', 'Hammers', 'Monk', 'Natural', 'Polearms', 'Siege Engines', 'Spears', 'Thrown', 'Tribal']

#add all of forests options
languages = ['Abyssal', 'Aklo', 'Aquan', 'Auran', 'Boggard', 'Celestial', 'Common', 'Cyclops', 'Dark Folk', 'Draconic', 'Druidic', 'Drow Sign Language', 'Dwarven', 'Elven', 'Giant', 'Gnoll', 'Gnome', 'Goblin', 'Grippli', 'Halfling', 'Ignan', 'Infernal', 'Kelish', 'Orc', 'Protean', 'Sphinx', 'Sylvan', 'Tengu', 'Terran', 'Treant', 'Undercommon', 'Vegepygmy', 'Vishkanya', 'Wayang']

#add all of forests options
deities = ['Abadar', 'Achaekek', 'Alseta', 'Ameiko Kaijitsu', 'Apsu', 'Aroden', 'Asmodeus', 'Black Butterfly, The', 'Brigh', 'Calistria', 'Cayden Cailean', 'Chaldira Zuzaristan', 'Chamidu', 'Daikitsu', 'Dahak', 'Desna', 'Elion', 'Erastil', 'Ghlaunder', 'Gorum', 'Gozreh', 'Groetus', 'Gruhastha, The', 'Hanspur', 'Hei Feng', 'Iomedae', 'Irori', 'Jaidi', 'Jingxi', 'Kabriri', 'Kazutal', 'Kelizandri', 'Ketephys', 'Kofusachi', 'Lama, The', 'Lamashtu', 'Magrim', 'Milani', 'Minderhal', 'Naderi', 'Nalinivati', 'Nethys', 'Nivi Rhombodazzle', 'Norgorber', 'Old-Mage Jatembe', 'Oras', 'Orcus', 'Pharasma', 'Qi Zhong', 'Ragathiel', 'Razmir', 'Rovagug', 'Sarenrae', 'Sivanah', 'Sivanah, The', 'Skrymir', 'Sokhna', 'Sun Wukong', 'Thamir Gixx', 'Thremyr', 'Torag', 'Urgathoa', 'Uskyeria', 'Wadjet', 'Weydan', 'Ydersius', 'Yuelral', 'Zagnexapan', 'Zargos', 'Zon-Kuthon' ]

alignment = ["Chaotic good", "Chaotic neutral", "Chaotic evil", "Lawful good", "Lawful neutral", "Lawful evil", "Neutral good", "True Neutral", "Neutral evil"]

hair_colors = ['Black', 'Brown', 'Blond', 'Red', 'White', 'Grey']

hair_types = ['Curly', 'Wavy', 'Straight', 'Flowing', 'Frizzy', 'Spiky', 'Touseled', 'Unkempt']

eye_colors = ['Amber', 'Blue', 'Brown', 'Grey', 'Green', 'Hazel']

appearance = ['Jewelry', 'Piercings', 'Formal Clothing', 'Ragged', 'Missing Teeth', 'Scar', 'Tattoos', 'Birthmark', 'Bald', 'Braided Hair', 'Twitch', 'Beautiful', 'Ugly']

#add all of forests options
profession = [
'Acrobat',
'Actor/Actress',
'Architect',
'Astronomer',
'Blacksmith',
'Bookbinder',
'Brewer',
'Butcher',
'Carpenter',
'Chef',
'Comedian',
'Crocheter',
'Debater',
'Detective',
'Diplomat',
'Dressmaker/Tailor',
'Electrician',
'Engineer',
'Escape Artist',
'Falconer',
'Farmer',
'Fencer',
'Fire Eater',
'Fisherman',
'Fletcher',
'Florist',
'Forger',
'Glassblower',
'Goldsmith',
'Gossip',
'Graffiti Artist',
'Gymnast',
'Herbalist',
'Hunter',
'Illusionist',
'Jeweler',
'Knife Thrower',
'Leatherworker',
'Linguist',
'Locksmith',
'Lumberjack',
'Makeup Artist',
'Martial Artist',
'Mathematician',
'Mechanic',
'Medium',
'Metalworker',
'Mime',
'Miner',
'Mountaineer',
'Navigator',
'Orator',
'Painter',
'Paraglider',
'Performer',
'Philosopher',
'Photographer',
'Pianist',
'Pirate',
'Poet',
'Potter',
'Puppeteer',
'Rafting Guide',
'Ranger',
'Roofer',
'Sailor',
'Sculptor',
'Singer',
'Skateboarder',
'Skiing/Snowboarding',
'Skydiver',
'Sleight of Hand Artist',
'Smuggler',
'Sniper',
'Snowshoeing',
'Speleologist/Caver',
'Stage Magician',
'Stonecutter',
'Swimmer',
'Tattoo Artist',
'Thief',
'Thrower',
'Trick Roper',
'Veterinarian',
'Ventriloquist',
'Weaponsmith',
'Weaver',
'Whittler',
'Wrestler',
'Writer',
'Yoga Instructor',
'Zookeeper',
'Acupuncturist', 'Animal Trainer', 'Antiques Dealer', 'Astrologer', 'Baker', 'Barista', 'Bartender', 'Beekeeper', 'Bonsai Grower', 'Botanist', 'Calligrapher', 'Cartoonist', 'Ceramicist', 'Chocolatier', 'Climber', 'Collector', 'Colorist', 'Comic Artist', 'Confectioner', 'Cosmetologist', 'Costume Designer', 'Critic', 'Cultural Historian', 'Cutler', 'Dance Instructor', 'Dental Technician', 'Dietitian', 'Diplomatic Courier', 'Director', 'Dog Breeder', 'Entertainer', 'Entrepreneur', 'Event Planner', 'Exotic Dancer', 'Fashion Designer', 'Film Critic', 'Firefighter', 'Fitness Trainer', 'Flair Bartender', 'Flight Attendant', 'Floral Designer', 'Food Critic', 'Forensic Scientist', 'Furniture Maker', 'Game Designer', 'Garden Designer', 'Genealogist', 'Glass Artist', 'Guitarist', 'Hair Stylist', 'Handwriting Expert', 'Headhunter', 'Historian', 'Home Stager', 'Ice Cream Maker', 'Image Consultant', 'Interior Designer', 'Jewelry Maker', 'Juice Maker', 'Karaoke Host', 'Karate Instructor', 'Landscape Architect', 'Lapidary', 'Latte Artist', 'Lighting Designer', 'Lockpick', 'Makeup Instructor', 'Marine Biologist', 'Massage Therapist', 'Mechanical Engineer', 'Mediator', 'Swing Dancing',
'Taxidermy',
'Tea Tasting',
'Technical Writing',
'Theatrical Makeup',
'Toy Making',
'Translation',
'Truffle Hunting',
'Typography',
'Video Editing',
'Virtual Reality Design',
'Visual Effects',
'Wax Sculpting',
'Web Development',
'Wedding Planning',
'Wildlife Biology',
'Wine Tasting'
]

#add all of forests options


#add all of forests options
mannerisms = ['Adjusts glasses', 'Bites fingernails', 'Bites lip', 'Blows bubbles', 'Brushes hair out of face', 'Bursts into laughter', 'Chews gum', 'Chuckles', 'Clicks pen', 'Clutches purse tightly', 'Combs hair with fingers', 'Covers mouth when speaking', 'Cracks knuckles', 'Crosses arms', 'Crosses legs', 'Curls up in a ball', 'Doodles', 'Drums fingers', 'Eyes dart around room', 'Fiddles with hair', 'Fidgets', 'Flexes muscles', 'Folds arms', 'Furrows brow', 'Gestures while talking', 'Glances at watch', 'Grins', 'Hides hands in pockets', 'Hugs oneself', 'Hums to oneself', 'Jingles keys', 'Jumps up and down', 'Laughs at own jokes', 'Leans back', 'Leans forward', 'Licks lips', 'Lifts eyebrows', 'Lifts chin', 'Licks teeth', 'Looks around nervously', 'Looks over glasses', 'Mumbles', 'Nervously clears throat', 'Nods often', 'Opens and closes mouth', 'Paces', 'Pats pockets', 'Peers over glasses', 'Plays with jewelry', 'Plays with sleeves', 'Pops knuckles', 'Puts hands in pockets', 'Raises eyebrows', 'Readjusts clothing', 'Rests chin in hand', 'Rests hand on hip', 'Rests head on hand', 'Rolls eyes', 'Rub hands together', 'Runs fingers through hair', 'Scratches head', 'Shakes head', 'Shifts weight from one foot to the other', 'Shrugs', 'Sighs', 'Smacks lips', 'Smiles', 'Smirks', 'Snaps fingers', 'Squints', 'Stares into space', 'Stares intensely', 'Stifles a yawn', 'Strokes chin', 'Sways back and forth', 'Sweats', 'Swings arms', 'Taps foot', 'Taps pencil', 'Thumbs through a book', 'Throws head back when laughing', 'Tilts head', 'Tucks hair behind ears', 'Twiddles thumbs', 'Twirls hair', 'Twists hair', 'Twitches', 'Winks', 'Wipes hands on pants', 'Wipes nose', 'Wipes sweat from forehead', 'Withdraws into oneself', 'Wring hands', 'Yawns', 'Yells when excited', 'Zones out', 'Bites lower lip', 'Bites upper lip', 'Blows nose', 'Brushes off clothes', 'Clenches fists', 'Clenches jaw', 'Combs mustache', 'Covers ears', 'Covers eyes', 'Crosses fingers', 'Crouches', 'Cups chin with hand', 'Dabs at eyes', 'Dons sunglasses', 'Drops head', 'Elevates eyebrows', 'Exhales audibly', 'Fans oneself', 'Fiddles with jewelry', 'Fingers lapel', 'Flips hair', 'Folds hands', 'Gathers hair into a ponytail', 'Glances away', 'Glances over shoulder', 'Gnaws on pencil', 'Grits teeth', 'Holds breath', 'Huffs', 'Jumps at sudden sounds', 'Kicks at the ground', 'Kneads fingers', 'Kneels', 'Lays head on desk', 'Leans on desk', 'Lift']

#add all of forests options
traits = ['ambitious', 'anxious', 'artistic', 'brave', 'calm', 'careless','charming', 'clever', 'compassionate', 'confident', 'creative','curious', 'daring', 'dependable', 'determined', 'discreet','distrustful', 'eccentric', 'emotional', 'energetic', 'enthusiastic','ethical', 'excitable', 'friendly', 'frustrated', 'generous','gloomy', 'graceful', 'grateful', 'gregarious', 'guarded', 'happy','hardworking', 'honest', 'humorous', 'imaginative', 'impatient','indecisive', 'independent', 'industrious', 'inquisitive', 'intelligent','introverted', 'kind', 'knowledgeable', 'logical', 'loyal', 'mature','methodical', 'modest', 'moody', 'naive', 'narcissistic', 'neurotic','optimistic', 'organized', 'outgoing', 'paranoid', 'passionate', 'patient','perfectionist', 'persistent', 'pessimistic', 'philosophical', 'playful','polite', 'practical', 'proactive', 'proud', 'quiet', 'quick-tempered','rational', 'reliable', 'reserved', 'resourceful', 'restless', 'romantic','sensitive', 'serious', 'shy', 'skeptical', 'sociable', 'solitary','spontaneous', 'stubborn', 'studious', 'submissive', 'suspicious','talkative', 'temperamental', 'thoughtful', 'thrifty', 'tolerant','trustworthy', 'unselfish', 'unstable', 'vain', 'virtuous', 'warmhearted','wary', 'witty', 
              'Adventurous', 'Affectionate', 'Aggressive', 'Analytical', 'Assertive', 'Cautious', 'Charismatic', 'Charming', 'Clever', 'Comical', 'Compassionate', 'Confident', 'Conservative', 'Considerate', 'Courageous', 'Cynical', 'Dependable', 'Determined', 'Devoted', 'Eccentric', 'Empathetic', 'Energetic', 'Enthusiastic', 'Excitable', 'Extroverted', 'Friendly', 'Gregarious', 'Hardworking', 'Idealistic', 'Innovative', 'Insightful', 'Intelligent', 'Intuitive', 'Inventive', 'Inquisitive', 'Jovial', 'Loyal', 'Meticulous', 'Mysterious', 'Objective', 'Observant', 'Optimistic', 'Organized', 'Outgoing', 'Passionate', 'Patient', 'Perfectionist', 'Persistent', 'Pessimistic', 'Practical', 'Protective', 'Rational', 'Realistic', 'Reliable', 'Reserved', 'Resourceful', 'Respectful', 'Responsible', 'Risk-taking', 'Romantic', 'Sarcastic', 'Skeptical', 'Sociable', 'Spontaneous', 'Stoic', 'Straightforward', 'Stubborn', 'Sympathetic', 'Tactful', 'Tenacious', 'Thoughtful', 'Trusting', 'Unconventional', 'Understanding', 'Unselfish', 'Vigilant', 'Visionary', 'Warm', 'Witty', 'Zealous']

#add all of forests options

traits_abilities = ["Absolute Loyalty",
"Accelerated Drinker",
"Ambush Training",
"Anatomist",
"Armor Expert",
"Axe to Grind",
"Battlefield Disciple",
"Berserker of the Society",
"Black Powder Bravado",
"Black Powder Fortune",
"Black Powder Interjection",
"Blade of the Society",
"Bloodthirsty",
"Bullied",
"Careful Combatant",
"Coherent Rage",
"Cold and Calculating",
"Courageous",
"Crowd Dodger",
"Dedicated Defender",
"Defender of the Society",
"Deft Dodger",
"Demon Slayer",
"Demon Smiter",
"Dirty Fighter",
"Disillusioned",
"Dispelled Battler",
"Dueling Cloak Adept",
"Easy Way or the Hard Way",
"Evasive Sting",
"Excitable",
"Faith's Hunter",
"Fencer",
"Firebug",
"Hard to Kill",
"Helpful",
"Hidden Hand",
"Hill Fighter",
"Holdout",
"Honored Fist of the Society",
"Hunter's Knack",
"Improvised Defense",
"Indelible Ire",
"Inspiring",
"Inspiring Rush",
"Jungle Fighter",
"Just Like New",
"Killer",
"Kin Guardian",
"Larger Than Life",
"Martial Performer",
"Muscle of the Society",
"Nature's Mimic",
"Never Stop Shooting",
"Pillager",
"Reactionary",
"Reckless",
"Reckless Contempt",
"Resilient",
"Resolve of the Rejected",
"River Fighter",
"Savanna Hunter",
"Scarred Descendant",
"Slippery",
"Soaring Sprinter",
"Sprint",
"Startling Report",
"Steel Skin",
"Strong Arm, Supple Wrist",
"Surprise Weapon",
"Sworn Enemy",
"Tactician",
"Threatening Defender",
"Tracker of the Society",
"Unblemished Barrel",
"Vengeful",
"Vigilant Battler",
"Weapon of Peace",
"Witty Repartee",
"Authoritarian",
"Beacon of Faith",
"Birthmark",
"Blessed",
"Blessed Touch",
"Called",
"Caretaker",
"Child of the Temple",
"Chosen One",
"Defy Madness",
"Devoted Healer",
"Devotee of the Green",
"Disdainful Defender",
"Ease of Faith",
"Exalted of the Society",
"Faithful Feedback",
"Fate's Favored",
"Fearless Defiance",
"First Memories",
"Focused Disciple",
"History of Heresy",
"Honest",
"Indomitable Faith",
"Inspired",
"Irrepressible",
"Loyalty across Lifetimes",
"Martial Manuscript",
"Mystery Initiate",
"Necrotic Aura",
"Oathbound",
"Omen",
"Patient Calm",
"Perpetual Companion",
"Planar Savant",
"Principled",
"Prophesied",
"Redeemer",
"Reincarnated",
"Sacred Conduit",
"Sacred Touch",
"Scholar of the Great Beyond",
"Schooled Inquisitor",
"Spell Intuition",
"Spirit Sense",
"Stalwart of the Society",
"Tireless Avenger",
"Unnatural Presence",
"Wanderer's Shroud",
"Zealot",
"Zealous Striker",
"Air-Touched",
"Alchemical Adept",
"Alchemical Intuition",
"Arcane Revitalization",
"Arcane Temper",
"Ascendant Recollection",
"Beast of the Society",
"Bladed Magic",
"Charlatan",
"Child of the Moon",
"Classically Schooled",
"Cross-Disciplined",
"Cross-Knowledge",
"Dangerously Curious",
"Deep Guardian",
"Desperate Resolve",
"Desperate Speed",
"Diabolical Dabbler",
"Distance Aptitude",
"Domineering",
"Earth-Touched",
"Earthbound",
"Eldritch Delver",
"Eldritch Smith",
"Enduring Mutagen",
"Fey Protection",
"Flame-Touched",
"Focused Burn",
"Focused Mind",
"Fortunate",
"Ghost Sight",
"Gifted Adept",
"Greater Adept of the Society",
"Greater Link",
"Greater Purpose",
"Havoc of the Society",
"Hedge Magician",
"Insistent Benefactor",
"Inured to Death",
"Keen Appraiser",
"Kin Bond",
"Knowledgeable Caster",
"Linked Surge",
"Lucid Dreamer",
"Magic Crafter",
"Magical Flair",
"Magical Knack",
"Magical Lineage",
"Magical Talent",
"Malleable Magic",
"Mathematical Prodigy",
"Meticulous Concoction",
"Mutant Eye",
"Naturally Gifted",
"Outcast's Intuition",
"Overwhelming Beauty",
"Partial Protege",
"Pathfinder's Focus",
"Perfectionist's Brew",
"Possessed",
"Pragmatic Activator",
"Precise Treatment",
"Reluctant Apprentice",
"Resilient Caster",
"Scorned by Magic",
"Second Tongue",
"Self-Taught Scholar",
"Shrouded Casting",
"Skeptic",
"Spark of Creation",
"Storm-Touched",
"Strength Foretold",
"Strength of the Land",
"Tenacious Shifting",
"Theoretical Magician",
"Transmuter",
"Trickster",
"Twinned Presence",
"Two-World Magic",
"Unscathed",
"Unseen but Not Undone",
"Unstable Mutagen",
"Volatile Conduit",
"Water-Touched",
"Acrobat",
"Adopted",
"Affable",
"Ambitious",
"Artisan",
"Avid Reader",
"Bastard",
"Beast Bond",
"Bruising Intellect",
"Bully",
"Calculated Bribe",
"Canter",
"Charming",
"Child of the Streets",
"Civilized",
"Clever Wordplay",
"Collector",
"Competitive",
"Contagious Mettle",
"Convincing Liar",
"Criminal",
"Cynical Ear",
"Destined Diplomat",
"Dismantle Order",
"Doublespeak",
"Enemy of Slavers",
"Etymologist",
"Explorer",
"Fast-Talker",
"Free Spirit",
"Friend in Every Town",
"Friends in High Places",
"Friends in Low Places",
"Gnomish Alchemist",
"Gregarious",
"Grief-Filled",
"Grim Optimism",
"Hardly a Fool",
"Harvester",
"Hell Knight Ancestry",
"Hunter's Blood",
"Imposing Scion",
"Influence",
"Knowing the Enemy",
"Law Enforcer",
"Life of Toil",
"Lost Nobility",
"Maestro of the Society",
"Mediator",
"Memorable",
"Mentored",
"Mercenary",
"Merchant",
"Natural-Born Leader",
"Noble Savage",
"Nonchalant Thuggery",
"Ordinary",
"Orphaned",
"Poverty-Stricken",
"Prince/Princess",
"Relic-Proof",
"Rest for the Wicked",
"Rich Parents",
"Savage",
"Savant",
"Secret-Keeper",
"Seeker",
"Signature Moves",
"Simple Disciple",
"Snowbound",
"Student of Philosophy",
"Style Sage",
"Supportive",
"Suspicious",
"Talented",
"Tireless Logic",
"Tropical Upbringing",
"Trustworthy",
"Truth's Agent",
"Unintentional Linguist",
"Unnatural Revenge",
"Unpredictable",
"Veiled Disciple",
"Wanderlust",
"Weathered Emissary",
"Without a Past",
"Worldly",
"Chance Savior",
"Inspired by Greatness",
"Making Good on Promises",
"On the Payroll",
"Subject of Study",
"Teacher’s Pet",
"Child of Infamy",
"Conspiracy Hunter",
"Diabolist Raised",
"Firebrand",
"Infernal Bastard",
"Shadow Child",
"The Pathfinder's Exile",
"Drug Addict",
"Framed",
"Love Lost",
"Missing Child",
"Unhappy Childhood",
"Best Friend",
"Caravan Guard",
"Childhood Crush",
"Foster Child",
"Friend of the Family",
"Hero Worship",
"Rescued",
"Student Survivalist",
"Younger Sibling",
"Bastard",
"Brigand",
"Issian",
"Noble Born",
"Pioneer",
"Riverlander",
"Sword Scion",
"Earning Your Freedom",
"Finding Your Kin",
"Gnoll Killer",
"Missionary",
"Reclaiming your Roots",
"Seeking Adventure",
"Blood of Pharaohs",
"Devotee of the Old Gods",
"Foreign Opportunist",
"Inquisitive Archaeologist",
"Mummy-Cursed",
"Necropolis Native",
"Resurrected",
"Sphinx Riddler",
"Trap Finder",
"Undead Crusader",
"Black Sheep",
"Favored Child",
"Outlander",
"Fools for Friends",
"Into Enemy Territory",
"Looking for Work",
"Optimistic Gambler",
"Researching the Blot",
"Scouting for Fiends",
"Boarded [A]",
"Boarded [B]",
"Boarded [C]",
"Boarded [D]",
"Colonial",
"Get the Cargo Through",
"Jungle Scholar",
"Ship's Crew",
"Stowaway",
"Alabaster Outcast",
"Exchange Agent",
"Former Assassin",
"Monument Scholar",
"Nontraditional Native",
"Ruin Raider",
"Serpent Runner",
"Ancient Explorer",
"Barroom Talespinner",
"Buccaneer's Blood",
"Dockside Brawler",
"Eye for Plunder",
"Native",
"Natural Born Sailor",
"Peg Leg",
"Ship's Surgeon",
"Touched by the Sea",
"Augmented Disguise",
"Dealmaker",
"Extremely Fashionable",
"Heirloom Weapon",
"Improvisational Equipment",
"Iron Liver",
"Power of Suggestion",
"Prehensile Whip",
"Quick Learner",
"Rough and Ready",
"Stage Magic",
"Stealthy Escape",
"Thrown-Together Fashion",
"A Sure Thing",
"Aid Allies",
"Attuned to the Ancestors",
"Bad Reputation",
"Beneficient Touch",
"Captain's Blade",
"Comparative Religion",
"Dervish",
"Desert Shadow",
"Devil's Mark",
"Dunewalker",
"Eastern Mysteries",
"Expert Duelist",
"Fashionable",
"Fiendish Presence",
"Fires of Hell",
"Force For Good",
"Fortified",
"Goldfinger",
"Greasy Palm",
"Horse Lord",
"Hunter's Eye",
"I Know a Guy",
"Impressive Presence",
"Indomitable",
"Insider Knowledge",
"Loyalty",
"Master of Pentacles",
"Medic",
"Meridian Strike",
"Meticulous Artisan",
"Mind Over Matter",
"Mummy-Touched",
"Observant",
"Performance Artist",
"Proper Training",
"Saint's Ward",
"Secrets of the Sphinx",
"Shadow Diplomat",
"Shiv",
"Sotto Voce",
"Soul-Drinker",
"Storyteller",
"Teaching Mistake",
"Tomb Raider",
"Trouper",
"Unorthodox Strategy",
"Vindictive",
"Watchdog",
"Weapon Style",
"Blood of Dragons",
"Deathtouched",
"Fiend Blood",
"Adaptable Flatterer",
"Adrift",
"Advantageous Distraction",
"Adventurous Explorer",
"Aerial Observer",
"Alchemical Breath",
"Almost Human",
"Animal Friend",
"Animalistic Affliction",
"Anticipate Evil",
"Arcane Dabbler",
"Arcane Student",
"Arms Master",
"Artistic Dilettante",
"Aspiring Bard",
"Assimilated Native",
"Auspicious Tattoo",
"Balloon Headed",
"Beast Bully",
"Bent Body",
"Big Boned",
"Big Ears",
"Blade Bravado",
"Blessing of Darkness",
"Blood Stalker",
"Boar Resilience",
"Bog Scamp",
"Born Damned",
"Born in the Light",
"Born to the Water",
"Bouncy",
"Bralani's Step",
"Bred for War",
"Brewmaster",
"Brute",
"Buried Anxiety",
"Burnished Skin",
"Caravan Drover",
"Carefully Hidden",
"Carnation Scales",
"Celestial Tracker",
"Centaur Vengeance",
"Chain Master",
"Child of Platinum",
"Clearheaded",
"Clergy Member",
"Cold Fortitude",
"Colonial Entitlement",
"Colonial Sympathizer",
"Color Thief",
"Creative Manipulator",
"Crocodile Swim",
"Curse in the Blood",
"Dark Magic Affinity",
"Deadly Rush",
"Death’s Deputy",
"Deathkeeper",
"Deep Marker",
"Dilettante Artist",
"Dog-Sniff-Hate",
"Dowsing",
"Draconic Echo",
"Durable Change",
"Elaborate Trapper",
"Elven Reflexes",
"Elven Serenity",
"Enlightened Warrior",
"Ethical Leader",
"Ever Home",
"Ever Wary",
"Eyes of the Sun",
"Failed Apprentice",
"Faith Healer",
"Family Connections",
"Fanatic",
"Fanatic",
"Feline Instinct",
"Fiery Glare",
"Fight with the Flock",
"Final Embrace",
"Finish the Fight",
"Fire-Tongued",
"Firebug",
"Flair for Destruction",
"Following Breeze",
"Forlorn",
"Foul Belch",
"Freed Slave",
"Freedom Fighter",
"Freedom Fighter",
"Friendless",
"Frost Spitter",
"Genie Blood",
"Glib Barrister",
"Goblin Foolhardiness",
"God Scorn",
"Golden Scales",
"Goldsniffer",
"Good Influence",
"Grounded",
"Half-Forgotten Secrets",
"Harrow Born",
"Harrow Chosen",
"Heat Fortitude",
"Helpful",
"Historian",
"Horse Lord",
"Ice Walker",
"Icy Mementos",
"Inciter",
"Infernal Influence",
"Inheritor",
"Inheritor",
"Innocent",
"Inured to Disease",
"Iron Control",
"Keeper of the Ancestral Scrolls",
"Kobold Faith",
"Kobold Herbalist",
"Lantern Spirit",
"Latent Psion",
"Legacy of Sand",
"Lettered",
"Lightning-Blessed",
"Lillend's Harp",
"Linguistic Genius",
"Liquid-Tongued",
"Lycanthropic Bloodlust",
"Market Rat",
"Martyr's Blood",
"Master of the Sudden Strike",
"Masterful Demeanor",
"Mastery of Form",
"Militant Merchant",
"Mind Trapper",
"Motherless",
"Nomadic",
"Numerological Gift",
"Old Before Your Time",
"Ooze Defense",
"Open Hand and Mind",
"Operatic",
"Outcast",
"PAGE MISSING",
"Pain Artist",
"Pearl Diver",
"Perfect Servant",
"Planar Negotiator",
"Planetar's Visions",
"Practiced Impression",
"Prayer Breaker",
"Precision Hearing",
"Pride of the Diamond Empire",
"Prideful Temper",
"Prolong Magic",
"Proud Tribesman",
"Providential Passenger",
"Purple Scales",
"Pustular",
"Pyromancer",
"Rapscallion",
"Rat Squeeze",
"Relic Hunter",
"Repel Sin",
"Repulsive",
"Reviving Rest",
"Rude Songs",
"Ruthless",
"Sandy Ambush",
"Scholar of Ruins",
"Scrapper",
"Scrounger",
"Seeker of Brightness",
"Selective Health",
"Sensual Graces",
"Shadow Stabber",
"Shared Curse",
"Sharkchild",
"Shield Bearer",
"Shift the Blame",
"Shoreline Skirmisher",
"Skater's Balance",
"Slave Smuggler",
"Slaver",
"Slippery Step",
"Slithering Stride",
"Smoke Resistant",
"Snake Hater",
"Snap Ignition",
"Sneaky Swimmer",
"Soul Eater",
"Speech of the Wilds",
"Sphinxfriend",
"Spirits in the Stone",
"Stargazer",
"Stoic Dignity",
"Strength of Body",
"Successful Shirker",
"Suicidal",
"Superior Clutch",
"Superstitious",
"Tattooed Mystic",
"Tempter's Tongue",
"Terrifying Lunge",
"Thoroughbred",
"Thrall Spotter",
"Tiger's Claw",
"Tongue of Many Towns",
"Tough Skin",
"Toxophilite",
"Trade Talk",
"Trailblazer",
"Traumatic Shift",
"Trifler",
"Tropical Botanist",
"Tunnel Fighter",
"Twilight Zeal",
"Ugly Swine",
"Undead Slayer",
"Underling",
"Undine Loyalty",
"Unearth Secrets",
"Unidentifiable Appeal",
"Vermin Wrangler",
"Vile Kiss",
"Voice of Velvet",
"Warrior of Old",
"Warsmith",
"Wary",
"Well-Informed",
"World Traveler",
"Youthful Mischief",
"Zest for Battle",
"Aberration Hunter",
"Acupuncturist",
"Addicted",
"Advocate for the Empire",
"Alchemical Prodigy1",
"Alchemical Prodigy2",
"Alien Origins",
"Altruistic Diplomat",
"Antiquities Smuggler",
"Arbiter",
"Arcane Dabbler",
"Arcane Graduate",
"Archeologist",
"Armor Master",
"Artifact Hunter",
"Aspiring Hell Knight",
"Bandit",
"Blood Steed",
"Blooded",
"Border Guard",
"Born Rider",
"Bounty Hunter",
"Brave",
"Briar Bandit",
"Builder's Apprentice",
"Candidate for Perfection",
"Cavalry Rider",
"Charger",
"Cheap to Feed",
"Child of the Crusades",
"Chivalrous",
"Chosen Child",
"City Defender",
"Clan Artisan",
"Cliff Jumper",
"Cliff-Master",
"Clumsy Slave",
"Coin Hoarder",
"Coincunning",
"Cold Heart",
"Community-Minded",
"Confidante to the Oppressed",
"Conscientious Miner",
"Construct Crafter",
"Cosmopolitan",
"Crusader Tactician",
"Cynic",
"Cypher Resistance",
"Darklands Delver",
"Dealer1",
"Dealer2",
"Demon Eradicator",
"Demon Slayer",
"Desert Child",
"Desert Nomad",
"Destined For Greatness",
"Devotee of the Holy Prophecies",
"Dim Seer",
"Diplomat",
"Disbeliever1",
"Disbeliever2",
"Discerning Beliefs",
"Disease Resistant",
"Diver",
"Dominator",
"Draconic Vigil",
"Dump Salvager",
"Dungeon Dweller",
"Dusk Agent",
"Dusk Agent",
"Dusk Dancer",
"Elemental Pupil",
"Emissary",
"Enemy of the Dead",
"Equality for All",
"Expert Smuggler",
"Eye of the Falcon",
"Famed Performer",
"Fixer",
"Flotsam",
"Freed Slave1",
"Freed Slave2",
"Freedom Fighter",
"Freedom Fighter",
"Freedom Fighter",
"Friend of the Dead",
"Friend of the Fey",
"Frontier-Forged",
"Frostborn",
"Gallant Imposter",
"Gatekeeper",
"Genie-Caller",
"Glory of Old",
"Gravelwalker",
"Great Market Merchant",
"Grit Goggles",
"Group Fighter",
"Guerilla",
"Guide of the Streets",
"Heart of Clay",
"Heavenly Touch",
"Heavy Hitter",
"Highlander",
"Hobgoblin Slayer",
"Honeyed Tongue",
"Humble Beginnings",
"Hunter of Outsiders",
"Imperial Soldier",
"Inspiring Speaker",
"Instigator of Rebellion",
"Iron Lungs",
"Iron Mind",
"Jungle Guide",
"Jungle Walker",
"Kami Talker",
"Keeper of the Veil",
"Knowledgeable Citizen",
"Knowledgeable Citizen",
"Lair Snake",
"Left Behind",
"Lesser Noble",
"Lightning Rider",
"Local Know-It-All",
"Long Jumper",
"Lost Role Model",
"Lucky Turnabout",
"Mammoth Master",
"Master Illusionist",
"Master of Peaks",
"Merchant’s Child",
"Militia Veteran",
"Miner",
"Mordant Heritage",
"Mountain Guide",
"Natural Artist",
"Natural Climber",
"Navigator",
"Noble",
"Numerologist",
"On Guard",
"Open-Minded Explorer",
"Orc Impaler",
"Orphan",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"Paragon of Speed",
"Pearl Diver",
"Perseverance",
"Pirate",
"Pirate2",
"Plainsman",
"Pomp and Pageantry",
"Powerful Bloodline",
"Precocious Spellcaster",
"Privileged Slave",
"Prospector",
"Purchased Loyalty",
"Pure Legion Recruit",
"Quick Reactor",
"Rabble Rebel",
"Rebel Leader",
"Reformed Acolyte",
"Region's Finest",
"Regional Influence",
"Regional Recluse",
"Resilient",
"Resolute",
"Rice Runner",
"River Rat",
"Riverfolk",
"Savage Breaker",
"Savannah Child",
"Sea-Souled",
"Seafarer",
"Seasoned Climber",
"Secret Cultist",
"Shadowcaster",
"Signaler",
"Signature Spell",
"Silent Hunter",
"Silent Watcher",
"Silvertongued",
"Sky Spirit Worshiper",
"Slayer of the Deep",
"Smuggler",
"Snake Bleeder",
"Snowstride",
"Soldier of the Faith",
"Sound of Mind",
"Spell Duel Prodigy",
"Spellpiercer",
"Spiritual Forester",
"Stable",
"Storm Hunter",
"Stormrunner",
"Stream Nomad",
"Suck In Your Gut",
"Sun Orchid Harvester",
"Superstitious",
"Superstitious Ward",
"Surface Stranger",
"Survivalist",
"Survivalist",
"Survivor",
"Swamp Rebel",
"Swamp Survivor",
"Swordsman's Page",
"Talented Blacksmith",
"Tattooed Wanderer",
"Tattooed Wanderer",
"Technic Tinkerer",
"Temple Guard",
"Tiger Brigadier",
"Touched of the Gods",
"Town Gossip",
"Trained Medic",
"Trap Savvy",
"Traveling Merchant",
"Tribesman",
"True Believer",
"Tundra Child",
"Underworld Explorer",
"Urchin",
"Vagabond Child",
"Veteran Jungle Guide",
"Viking Blood",
"Walking Ward",
"Warrior Poet",
"Wastes Explorer",
"Wayang Spellhunter",
"Well Bred",
"Wharf Rat",
"Whole-Hearted",
"Winter Warrior",
"Winter’s Soul",
"Woodland Diplomat",
"A Shining Beacon",
"Affinity of the Elements",
"Agent of Chance",
"Alluring",
"Ambassador",
"Arcane Depth",
"Backstabber",
"Battlefield Caster",
"Battlefield Surgeon",
"Blade of Mercy",
"Blessing of the Feast",
"Broken Mind",
"Call for Help",
"Centered",
"Child of Nature",
"Cleansing Light",
"Cleansing the Twisted",
"Contract Master",
"Corpse Cannibal",
"Corpse Hunter",
"Courtesan",
"Dawn Renewal",
"Deathspeaker",
"Deck Fighter",
"Defensive Strategist",
"Deformed",
"Demon Hunter",
"Demonic Persuasion",
"Destructive Blows",
"Devotee of a Dead God",
"Divine Warrior",
"Ear for Music",
"Elven Pantheist",
"Empty Heart, Full Heart",
"Empyreal Focus",
"Eye of the Father",
"Eyes and Ears of the City",
"Eyes of the Wild",
"Faithful Artist",
"Faithful of the Dead God",
"Fatal Trapper",
"Fiendish Confidence",
"Flame of the Dawn",
"Flounderer",
"Fortified Drinker",
"Good Dreams",
"Good Natured",
"Guardian of the Forge",
"Hatred of the Gods",
"Holy Schemer",
"Honey-Tongued",
"Honeyed Words",
"Illuminator",
"Inner Beauty",
"Inoculated",
"Intense Artist",
"Iron Grip",
"Know the Land",
"Loreseeker",
"Lover of the Law",
"Magic is Life",
"Mother's Rage",
"Mother’s Teeth",
"Nimble Fingers, Keen Mind",
"Opener of Doors",
"Opportunistic",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"PAGE MISSING",
"Pain Is Pleasure",
"Pantheist",
"Patient Optimist",
"Peacemaker",
"Potent Concoctions",
"Practiced Deception",
"Propitiation",
"Provider",
"Purity of Faith",
"Resigned",
"Restless Hunger",
"River Freedom",
"Sacred Avenger",
"Sacred Smasher",
"Scaly Ally",
"Searing Beacon",
"Second Chance",
"Secret Knowledge",
"Seer of Reality",
"Self-Sacrifice",
"Sense of Order",
"Sensing Imperfection",
"Serpentine Squeeze",
"Shadow Caster",
"Shadow Whispers",
"Spirit Guide",
"Spirit Talker",
"Starchild",
"Stoic Optimism",
"Strength of the Barghest",
"Strength of the Sun",
"Strip the Veils",
"Strong Heart",
"Strong Swimmer",
"Strong Willed",
"Talented Organizer",
"The City Protects",
"The Flexing Arm",
"Toilcrafter",
"Undead Slayer",
"Under Siege",
"Underlying Principals",
"Unhinged Mentality",
"Unspeakable Bond",
"Venom-Drenched",
"Veteran of Battle",
"Vindictive Strike",
"Voice of Monsters",
"Wasp Whisperer",
"Wisdom in the Flesh",
"Wise Teacher",
"Wolf Cub",
"Boarded [E]",
"Marked by Unknown Forces",
"No Escape",
"Unpredictable Reactions",
"Balancer's Banishing",
"Unabashed Gall",
"Amiable Blunder",
"Inexorable Authority",
"Elemental Endowment",
"Justiciar",
"Commercial Savvy",
"Evident Supporter",
"",
"Corpse Dodger",
"Child of the Necropolis",
"Unflinching Faith",
"Ghost Survivor",
"Ghoulish Affinity",
"Forbidden Knowledge",
"Holy Tattoo",
"Exiled Scholar",
"Alabaster Odalisque",
"Storm Pilot",
"Deepsea Native",
"Planar Scholar (Plane of Air)",
"Airship Captain (Plane of Air)",
"Channel the Earth (Plane of Earth)",
"Agent of the Sultana (Plane of Earth)",
"Solidarity (City of Brass)",
"Betrayed Ex-Noble (City of Brass)",
"Planar Historian (Plane of Water)",
"Aquatic Survivalist (Plane of Water)",
"Thoughtful Wish-Maker (Plane of Fire)",
"Fiery Dominance (Plane of Fire)",
"Whiteout (Undine)",
"Marid's Fury (Undine)",
"Wind-Carried Voices (Sylph)",
"Thunderborn (Sylph)",
"Instant Friendship (Suli)",
"Dualborn (Suli)",
"Statuesque (Oread)",
"Unflappable Arrogance (Ifrit)",
"Earthsense (Oread)",
"Expert Distractor (Ifrit)",
"Light Sleeper",
"Alchemists Apprentice",
"Detect Disobedience",
"Passionate Inertia",
"Subjective Truth",
"Wicked Leader",
"Bloody-Minded",
"Punish Insurrection",
"Horrifying Mind",
"Divine Deceiver",
"Obsequious Morsel",
"Shadowsight",
"Wardbreaker",
"Alert",
"Cooperative Combatant",
"Born under the Stranger",
"Awakened from Stasis",
"Scarred by Space Pirates",
"Lunar Birth ",
"Sun-Blessed ",
"Cellular Match",
"Nanite Revival",
"Adroit",
"Spidery Climber ",
"Skilled Telepath",
"Tactile Telekinesis",
"Transitional",
"Triaxian Dragonslayer ",
"Persuasive",
"Aballonian Resilience",
"Born under the Green Star",
"Eoxian Experiment",
"Triaxian Tradition",
"Akitonian Ferocity",
"Void Child",
"Skymetal Affinity",
"Offspring of the Ascension",
"Self-Reliant"]

version = "1.1.4"